### ISSUE TITLE
0.16.0 editor-wang bug

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#10]
![image](https://user-images.githubusercontent.com/13896536/125735389-b57ffa8b-93ea-443b-bafd-e192eaf2b89a.png)
按回车控制台报错

**Comment by greper** [comment]
搞不定这个bug，quill2年没发新版本了，打算移除它了

**Comment by levin950825** [comment]
好勒 ，另外一个用的更广点
