### ISSUE TITLE
context等变量，需要ts类型支持

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#102]
## 一、问题描述
如题，有些变量还未支持`ts`，导致代码中对应部分飘红

### 代码截图
![image](https://user-images.githubusercontent.com/5880014/196606021-e389b6d0-3f39-4079-a6a4-cb5233b5e162.png)

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.3.0",
    "@fast-crud/ui-antdv": "^1.3.0",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv ("^3.2.9")

### 3. 使用的admin框架
- [x] fs-admin-antdv

**Comment by greper** [comment]
升级到1.5.0试试
