### ISSUE TITLE
form.labelWidth 设置了不生效

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#105]
## 一、问题描述
设置了`form.labelWidth='300px'`并未生效

### 代码截图
![image](https://user-images.githubusercontent.com/5880014/198217742-abfd71c4-d58a-4b5f-8485-717e6778f06b.png)

#### 1. 期望效果
生效

#### 2. 实际效果
![image](https://user-images.githubusercontent.com/5880014/198217908-c996d8bd-750a-425d-90f3-ad026f805240.png)

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.3.0",
    "@fast-crud/ui-antdv": "^1.3.0",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (^3.2.9)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
antdv 的没有labelWidth参数
要设置antdv label宽度可以参考a-form-item文档：
https://www.antdv.com/components/form-cn#components-form-demo-lable-width

或者设置：labelCol， 和wrapperCol

**Comment by jingjingzhao** [comment]
我发现还必须同时设置 `display: "flex"`，否则不生效
