### ISSUE TITLE
配置了form.group，提交时有办法提示所有tab下的必填项吗

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#106]
## 一、问题描述
配置了form.group，提交时有办法提示所有tab下的必填项吗？
比如配置了「语音」、「文本」两个tab，其中所有字段都是必填的。在提交时，用户未填写第二个tab「文本」下的字段。必须切到「文本」tab才能看到必填项提示。体验不友好。有什么其他办法吗？

### 代码截图
![image](https://user-images.githubusercontent.com/5880014/198228045-45e8274f-95f2-421f-9967-331cb553ef07.png)

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.3.0",
    "@fast-crud/ui-antdv": "^1.3.0",

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (^3.2.9)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
嗯 可以考虑将tab页签（文本）标红，后续有空再看看如何实现吧

**Comment by greper** [comment]
已实现，由于tab不支持自定义className，所以需要自己写slot，具体参考示例：表单分组（tabs）
