### ISSUE TITLE
表单提交时，能否默认支持按钮loading态

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#107]
## 一、问题描述
目前表单提交时，按钮快速点击会导致多次调用接口

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.3.0",
    "@fast-crud/ui-antdv": "^1.3.0",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (^3.2.9)
### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
默认是有loading状态的，不知道你是什么情况没有loading的？
![image](https://user-images.githubusercontent.com/1687298/200097548-46e24185-649a-4086-bf1d-8a0df8610ac9.png)
