### ISSUE TITLE
布局样式建议

### ISSUE THREAD

**Issue by qq449245884** [fast-crud/fast-crud#115]
![0c469e4f359e3d1b2e86c3d14b48f2a](https://user-images.githubusercontent.com/35094245/202060517-a6319a76-bdf4-4da3-9676-ac413766be52.png)

希望能增加一些分块样式，就是表格，和搜索区域各用一个 card 来包起来。这样看起来会比较清晰。模块也比较明显。

**Comment by greper** [comment]
1.6.0 已支持
http://fast-crud.docmirror.cn/guide/advance/layout.html
