### ISSUE TITLE
表格列配置 compute 只在初始化的时候生效

### ISSUE THREAD

**Issue by lidongcheng88** [fast-crud/fast-crud#116]
#### 1. 期望效果
随着行数据的改动，动态改变 compute 值

#### 2. 实际效果
![image](https://user-images.githubusercontent.com/45726708/202190668-b27c8d09-9c6e-414b-8757-a78e95eb420c.png)
只在初始化的时候是有效的，编辑，刷新都还是原来的

### 2. 使用的ui库以及版本
- [x] ElementPlus（版本？）

### 3. 使用的admin框架
- [x] cool-admin

**Comment by greper** [comment]
1.6.0以上已修复
