### ISSUE TITLE
FsSearch组件的buttonsPosition和collapse配置项无效

### ISSUE THREAD

**Issue by NewYouth123** [fast-crud/fast-crud#125]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`FsSearch组件的buttonsPosition和collapse配置项无效`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
![image](https://user-images.githubusercontent.com/44632617/205566291-65e70952-11a6-4daa-a22e-db5645bdfa49.png)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 2. 实际效果
![image](https://user-images.githubusercontent.com/44632617/205566051-70abc2e5-cf51-42ed-aae6-60e1d544899e.png)

### 1. fast-crud版本：1.6.1
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [x] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
collapse 配置无效问题已修复
buttonsPosition 配置已移除（现在search的布局有点乱，大家如果有更好的布局可以推荐）
