### ISSUE TITLE
建议：crud的弹出框希望能够支持拖动

### ISSUE THREAD

**Issue by NewYouth123** [fast-crud/fast-crud#126]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`建议：crud的弹出框希望能够支持拖动`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图1`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![B}0~A%1Z%NPN4VD@07%A F9](https://user-images.githubusercontent.com/44632617/205566962-c21fca33-b5a3-4a3f-b75c-c3b5e01a2795.png)

### 1. fast-crud版本：
`1.6.1`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（版本2.34.2）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [x] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.8.0 已支持
