### ISSUE TITLE
crud的对话框和抽屉始终在第一次弹出没有动画，特别生硬

### ISSUE THREAD

**Issue by NewYouth123** [fast-crud/fast-crud#129]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`fs-admin-naive下crud的对话框始终在第一次弹出没有动画，很生硬，特别在edge浏览器下，停顿很长时间才弹出`

### 复现步骤
`请描述复现问题的详细步骤`
`新增-修改-查看弹出的对话框在第一次出现没有任何动画`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
![QQ图片20221228150428](https://user-images.githubusercontent.com/44632617/210721340-89caf001-005a-4bed-9f90-33a02eb28c03.jpg)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [x] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.8.4已修复
