### ISSUE TITLE
查看内容全局纯文本显示，目前只能单个字段实现

### ISSUE THREAD

**Issue by xyzsd0512** [fast-crud/fast-crud#132]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`view查看的话纯文本显示，目前的方法只能单个字段来是先，无法全局实现`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [x] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
可以试试这个配置
http://fast-crud.docmirror.cn/api/crud-options/settings.html#viewformusecellcomponent
