### ISSUE TITLE
【求助】column和search的type不一致如何实现？

### ISSUE THREAD

**Issue by iceking2nd** [fast-crud/fast-crud#135]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
能否提供一个column类型和search类型不一致的配置示例？

### 复现步骤
无

### 代码截图
无

### 报错截图
无

### 效果截图
在表格中字段显示为
<img width="96" alt="image" src="https://user-images.githubusercontent.com/2940204/212740456-52e3864d-e215-4823-a9b3-c7dafe361924.png">
在搜索时使用
<img width="264" alt="image" src="https://user-images.githubusercontent.com/2940204/212740564-5c80fd01-648f-463b-b337-5cb785158ea8.png">

#### 1. 期望效果
在table中的colunm里type为datetime，在搜索组件中使用datetimerange搜索一个时间段范围内的记录。

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
```
columns:{
  key:{
    type: 'datetime'
    search:{
         component:{
         name: 'el-datetimerange'
         }
     }
  }
}
```

**Comment by greper** [comment]
![image](https://user-images.githubusercontent.com/1687298/212786047-447736f5-4b95-4863-b524-330cd38b01d8.png)
