### ISSUE TITLE
将字典的数据存放在store，可以更好低与应用的业务逻辑结合。

### ISSUE THREAD

**Issue by crstudio** [fast-crud/fast-crud#136]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
假设有两个页面，
A页面：图书分类管理
B页面：图书管理
当两个页面同时打开的时候，再A页面新增一个图书分类，再再B页面添加图书时，B页面的图书分类下拉框是不会有刚才新增加的图书分类的。

#### 1. 期望效果
希望字典相关组件可以出一个方便与 vue 的store对接的方法或接口。

### 1. fast-crud版本：
1.8.3
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] ElementPlus（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-element

**Comment by greper** [comment]
不需要用store，数据字典直接支持页面间共享

http://fast-crud.docmirror.cn/antdv/#/crud/dict/shared/manager

http://fast-crud.docmirror.cn/antdv/#/crud/dict/shared/use
