### ISSUE TITLE
如何在fs-form组件中使用dict-select呢

### ISSUE THREAD

**Issue by coco-w** [fast-crud/fast-crud#137]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
如何在fs-form组件中使用dict-select？type直接设置成dict-select回显示成为input输入框,
crudConfig中columns应该如何设置呢
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`
```vue
<fs-form
  ref="formRef"
  v-bind="formOptions"
/>
<script lang="ts">
const formRef = ref()
const formOptions = ref({
  columns: {
    type:{
      title: 'title',
      align: "center",
      type: "dict-select",
      search: { show: false },
      dict: dict({
        [],
        value: "key",
        label: "val",
      })
    }
  }
})

</script>
```
### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`1.6.1`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
fs-form 是单独使用？
请把你的代码贴出来

**Comment by coco-w** [comment]
> fs-form 是单独使用？ 请把你的代码贴出来

贴出来了

**Comment by greper** [comment]
直接传formOptions的话，它接受的字段参数类型为：http://fast-crud.docmirror.cn/d.ts/modules.html#FormItemProps

```
const formOptions = ref({
  columns: {
    type:{
      title: 'title',
      align: "center",
      component:{
        name:'fs-dict-select',
        dict: dict({
        [],
        value: "key",
        label: "val",
      })
     }
    }
  }
})
```

如果你想要用crudOptions的写法来单独使用fs-form的话
请参考复用crudOptions示例（buildFormOptions的使用）
https://gitee.com/fast-crud/fs-admin-antdv/blob/main/src/views/crud/form/independent/index.vue#L44
http://fast-crud.docmirror.cn/antdv/#/crud/form/independent
