### ISSUE TITLE
0.17.0 BUG反馈

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#14]
![image](https://user-images.githubusercontent.com/13896536/128139477-49fa4a4a-1ca5-485b-89f9-b0c2544379c2.png)
指定 order 排序无效

**Comment by greper** [comment]
无法复现，我这边示例没有问题

**Comment by levin950825** [comment]
在 0.17.1 验证可以，怀疑是 vite 缓存导致
