### ISSUE TITLE
需求：希望可以增加一个页面顶部的tab查询

### ISSUE THREAD

**Issue by wanpong007** [fast-crud/fast-crud#140]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
希望可以增加一个页面顶部的tab查询，因为现在直接用组件字段配置是配置不出来的，当然现在可以用插槽实现，但是和现在的框架结合不是太完美

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
![image](https://user-images.githubusercontent.com/9105472/217496786-37a3b0e6-28a0-429c-b195-3a3379ba0698.png)

### 报错截图
无报错

### 效果截图
`请贴出效果截图`
#### 2. 实际效果
![image](https://user-images.githubusercontent.com/9105472/217496977-9914a090-50c9-47e1-b0a8-f681d9b9c288.png)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`

- [ x] ElementPlus（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/antdv/#/crud/feature/tabs
