### ISSUE TITLE
Failed to resolve component: draggable 

### ISSUE THREAD

**Issue by jeffrey-bin** [fast-crud/fast-crud#144]
https://github.com/fast-crud/fast-crud/blob/adbe940f60e82a800fb66c572b66462af013e450/packages/fast-crud/src/components/toolbar/fs-table-columns-filter/index.vue#L49

位置如上，感觉toolbar的拖拽功能可有可无，可以考虑去掉

**Comment by greper** [comment]
同 https://github.com/fast-crud/fast-crud/issues/145
这个是误删了draggable 的import 导致的，今天修复
