### ISSUE TITLE
【需求】 希望添加fs-uploader上传扩展包对minio 存储的支持

### ISSUE THREAD

**Issue by zhaohejing** [fast-crud/fast-crud#149]
## 一、问题描述
需求: 希望添加fs-uploader 对minio 存储的支持。

### 1. fast-crud版本：
1.19.0
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/antdv/#/crud/component/uploader/s3
