### ISSUE TITLE
0.17.x BUG 反馈

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#16]
![image](https://user-images.githubusercontent.com/13896536/128334138-187d99e9-2bfb-4027-a037-292253ea4feb.png)

## 写法一
``` js
 expose.setSearchFormData({ form, mergeForm: { sex: content.sex[0], ...form } });
```

## 写法二
``` js
expose.setSearchFormData({ sex: content.sex[0], ...form });
```
 
两种写法均做尝试，再次调用 `expose.getSearchFormData()` 依旧是空

**Comment by greper** [comment]
已修复
