### ISSUE TITLE
cdn引入

### ISSUE THREAD

**Issue by ZhoufangErqiangu** [fast-crud/fast-crud#160]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`我尝试使用vite-plugin-cdn-import从cdn引入fast-crud，始终得到vue is not defined的报错。我猜测是全局变量名字或是其他依赖的问题，有没有人搞过？`

### 代码截图
`
import vue from "@vitejs/plugin-vue";
import { defineConfig } from "vite";
import eslintPlugin from "vite-plugin-eslint";
import { Plugin } from "vite-plugin-cdn-import";

// https://vitejs.dev/config/
export default defineConfig({
  base: "/",
  plugins: [
    ...Plugin({
      modules: [
        {
          name: "vue",
          var: "Vue",
          path: "https://unpkg.com/vue@3.2.47/dist/vue.runtime.esm-browser.prod.js",
        },
        {
          name: "vue-demi",
          var: "VueDemi",
          path: "https://unpkg.com/vue-demi@0.13.11/lib/index.mjs",
        },
        {
          name: "pinia",
          var: "Pinia",
          path: "https://unpkg.com/pinia@2.0.33/dist/pinia.esm-browser.js",
        },
        {
          name: "vue-router",
          var: "VueRouter",
          path: "https://unpkg.com/vue-router@4.1.6/dist/vue-router.esm-browser.js",
        },
        {
          name: "dayjs",
          var: "dayjs",
          path: "https://unpkg.com/dayjs@1.11.7/dayjs.min.js",
        },
        {
          name: "element-plus",
          var: "ElementPlus",
          path: "https://unpkg.com/element-plus@2.3.0/dist/index.full.min.mjs",
          css: "https://unpkg.com/element-plus@2.3.0/dist/index.css",
        },
        {
          name: "@fast-curd/fast-crud",
          var: "FastCrud",
          path: "https://unpkg.com/@fast-crud/fast-crud@1.11.1/dist/fast-crud.mjs",
          css: "https://unpkg.com/@fast-crud/fast-crud@1.11.1/dist/style.css",
        },
      ],
    }),
    vue(),
    eslintPlugin({
      include: ["src/**/*.ts", "src/**/*.vue", "src/*.ts", "src/*.vue"],
    }),
  ],
  define: {
    "process.env": {},
  },
  build: {
    sourcemap: true,
  },
});
`

### 报错截图
`Vue is not defined`

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
详细报错截图发一下

**Comment by ZhoufangErqiangu** [comment]
我重新搞了一下，换成iife的文件导入，现在其他大部分的包都工作正常，但是fast crud报错，如下图

![error](https://user-images.githubusercontent.com/45325262/227540881-0ab92b9a-dea9-4c99-9168-22a5a916874d.png)

vite.config如下

import vue from "@vitejs/plugin-vue";
import { defineConfig } from "vite";
import eslintPlugin from "vite-plugin-eslint";
import { Plugin, autoComplete } from "vite-plugin-cdn-import";

// https://vitejs.dev/config/
export default defineConfig({
  base: "/",
  plugins: [
    Plugin({
      modules: [
        autoComplete("vue"),
        {
          name: "vue-demi",
          var: "VueDemi",
          path: "https://cdn.jsdelivr.net/npm/vue-demi@0.13.11/lib/index.iife.min.js",
        },
        {
          name: "pinia",
          var: "Pinia",
          path: "https://cdn.jsdelivr.net/npm/pinia@2.0.33/dist/pinia.iife.min.js",
        },
        {
          name: "vue-router",
          var: "VueRouter",
          path: "https://cdn.jsdelivr.net/npm/vue-router@4.1.6/dist/vue-router.global.min.js",
        },
        {
          name: "element-plus",
          var: "ElementPlus",
          path: "https://cdn.jsdelivr.net/npm/element-plus@2.3.1/dist/index.full.min.js",
          css: [
            "https://cdn.jsdelivr.net/npm/element-plus@2.3.1/dist/index.min.css",
            "https://cdn.jsdelivr.net/npm/element-plus@2.3.1/theme-chalk/dark/css-vars.css",
          ],
        },
        {
          name: "dayjs",
          var: "dayjs",
          path: "https://cdn.jsdelivr.net/npm/dayjs@1.11.7/dayjs.min.js",
        },
        {
          name: "@fast-curd/fast-crud",
          var: "FastCrud",
          path: "https://cdn.jsdelivr.net/npm/@fast-crud/fast-crud@1.11.7/dist/fast-crud.umd.min.js",
          css: "https://cdn.jsdelivr.net/npm/@fast-crud/fast-crud@1.11.7/dist/style.css",
        },
      ],
    }),
    vue(),
    eslintPlugin({
      include: ["src/**/*.ts", "src/**/*.vue", "src/*.ts", "src/*.vue"],
    }),
  ],
  define: {
    "process.env": {},
  },
  build: {
    sourcemap: true,
  },
});

**Comment by greper** [comment]
还需要加入
@fast-crud/ui-interface
@fast-crud/ui-element

**Comment by ZhoufangErqiangu** [comment]
还是报错找不到fast crud ui interface，

而且window下面还挂了个antdv，蛮神秘的

![error](https://user-images.githubusercontent.com/45325262/227690461-77ee1c49-6d45-41bd-a086-6dd69749a819.png)

我弄了个测试的仓库，你试试。

https://github.com/ZhoufangErqiangu/fast-cdn

**Comment by ZhoufangErqiangu** [comment]
看了一下，应该是vite配置的问题

源码里的大部分都改过了，可能等1.11.9就会好了？

我又仔细查了一下，@element-plus/icons-vue的全局变量设的不对

应该是ElementPlusIconsVue，见下图

![图片](https://user-images.githubusercontent.com/45325262/228260669-c2a5ba67-baf9-46f1-80d3-261e9444c31c.png)

还有lodash-es在，不确定cdn引入lodash能不能行。

**Comment by ZhoufangErqiangu** [comment]
![截图 2023-06-23 13-09-00](https://github.com/fast-crud/fast-crud/assets/45325262/b8c7af6b-1719-4df0-9871-2e5ee69eab08)
![截图 2023-06-23 13-09-20](https://github.com/fast-crud/fast-crud/assets/45325262/4d0f75e3-ede9-475f-a7cc-e52d921c1d96)

 蛮神秘的, 可以看到对象都挂在window下面了, 看不出这个ui interface是哪里require的

**Comment by ZhoufangErqiangu** [comment]
目前距离成功最近的方法是通过importmap引入esm

仍然会报没设置ui, 推测是浏览器把不同地方导入的ui-interface当作是不同的实例处理了

**Comment by greper** [comment]
你更新一下你的仓库，https://github.com/ZhoufangErqiangu/fast-cdn，我再看看这个ui-interface的问题

**Comment by ZhoufangErqiangu** [comment]
之前导入地址写错了, 开source map一看就找到问题了

现在可以正确从cdn加载了
