### ISSUE TITLE
文件上传BUG反馈

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#167]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`LIMIT = 10 多文件上传类型是数组，但是只传一个文件就是字符串`

### 代码截图

```
 imgAttrs: {
          title: "图片集",
          type: "image-uploader",
          column: {show: false},
          form: {
            component: {
              limit: 10,
              uploader: {
                type: "form"
              },
              valueType: "fileId",
              async buildUrls(value) {
                return new Promise((resolve) => {
                  resolve(GetFileUrl(value));
                });
              }
            },
            helper: "最大可上传10个文件"
          },
        },
```

### 效果截图

<img width="375" alt="image" src="https://user-images.githubusercontent.com/13896536/227405581-ce4321ef-eec0-48d8-b633-08176096d67c.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/13896536/227405587-c646bcc4-7fb4-4fda-a8b1-dfe892b43be7.png">

#### 1. 期望效果

如果limit != 1 应该都是数组

### 1. fast-crud版本：

1.11.7

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
无法复现
