### ISSUE TITLE
升级到1.11.8后页面报错

### ISSUE THREAD

**Issue by smallfuturess** [fast-crud/fast-crud#169]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`升级到1.11.8后页面报错`

### 复现步骤
`注释掉columns里面字段后不报错，$checked字段放出后继续报错`

### 代码截图
![O98C{(KILX{G@P@@ 3A8X{O](https://user-images.githubusercontent.com/17242501/227704043-150e26e7-e847-4f0c-853c-a44bcc8b0a21.png)

### 报错截图
![1679727494285](https://user-images.githubusercontent.com/17242501/227703894-7fbce932-1261-40fd-bc5e-488672ce5398.jpg)
![1679729984023](https://user-images.githubusercontent.com/17242501/227704203-d36fdd70-eb2f-4798-9794-2a76c7d849b5.jpg)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
试试1.11.9
