### ISSUE TITLE
0.17.x BUG反馈

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#17]
## 切换分页记录数未重置页码

![76101628737920_ pic_hd](https://user-images.githubusercontent.com/13896536/129133025-a45f19f1-c17e-4f84-b35b-7626e28d80ef.jpg)

## 日期查看打包后丢失（开发环境没问题）
![76141628738089_ pic_hd](https://user-images.githubusercontent.com/13896536/129133094-6285fe26-78f1-4660-ad20-8ce5d9b841e1.jpg)

**Comment by levin950825** [comment]
嵌套子表格本地不会错乱，打包后线上会错乱
![37F3C1F961340FA557752518A363A960](https://user-images.githubusercontent.com/13896536/129133180-39fac630-5cd1-4154-8240-70c91eb32de6.png)

**Comment by greper** [comment]
日期问题已修复
其他的后面再看

**Comment by greper** [comment]
0.17.5 已经可以重置页码

**Comment by levin950825** [comment]
@greper 重置页码已验证，但是打包后生产环境样式错位（PS：开发环境没问题）

**Comment by levin950825** [comment]
@greper 已验证
