### ISSUE TITLE
element limit=1时上传图片，删除后再选择相同图片，无法选中，选择其他图片就可以

### ISSUE THREAD

**Issue by lidongcheng88** [fast-crud/fast-crud#172]
![image](https://user-images.githubusercontent.com/45726708/228765834-c4bfa951-1d69-427b-ad7f-4a34baf1138a.png)

![image](https://user-images.githubusercontent.com/45726708/228765289-a688127d-6ee5-4040-abf0-876206a81320.png)

**Comment by lidongcheng88** [comment]
还有就是这个组件能增加个大图预览功能吗，因为我这边是用这个组件上传非 1:1 大图的，目前只有删除功能
![image](https://user-images.githubusercontent.com/45726708/228772251-c966d5c4-de04-4730-b657-ad59123e672b.png)

**Comment by greper** [comment]
1.12.0已支持
