### ISSUE TITLE
建议添加 search 中 引用自定义第三方组件 示例。

### ISSUE THREAD

**Issue by YeYinhai** [fast-crud/fast-crud#173]
## 一、问题描述
建议添加 search 中 引用自定义第三方组件 示例。方便新手学习。
![image](https://user-images.githubusercontent.com/9876526/229078935-3e52527c-8f07-49f8-b138-2d054365b900.png)

下面是我写的示例代码，大家可以暂时参考下。（组件套组件，多数情况并不需要这么麻烦）
### 代码截图
![image](https://user-images.githubusercontent.com/9876526/229079070-10ab7be2-4c0a-4a2a-a572-598c867451f8.png)

**Comment by greper** [comment]
已支持
http://fast-crud.docmirror.cn/antdv/#/crud/basis/custom
