### ISSUE TITLE
选择联动BUG

### ISSUE THREAD

**Issue by liaojinlong** [fast-crud/fast-crud#178]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
1.11.x 在搜索栏进行联动查询没问题，升级到 1.12.* 之后 getComponentRef("use_type_id$eq").reloadDict(); 就拿不到 getComponentRef("use_type_id$eq") 了，官方示例也是报错的

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
![image](https://user-images.githubusercontent.com/17539768/230519704-bb9cd04e-d089-4b28-b29c-03a6f8b3013a.png)

### 报错截图
![image](https://user-images.githubusercontent.com/17539768/230519782-d996f784-25df-4971-8af5-6e372fa2e3db.png)
![image](https://user-images.githubusercontent.com/17539768/230519793-cf11a2ff-1bd3-464a-9763-fb17d6215aca.png)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
1.12.2
### 2. 使用的ui库以及版本
- [] Antdv (版本？)
- [x ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`请注明`

**Comment by greper** [comment]
1.13.0已修复
