### ISSUE TITLE
form 表单 switch 组件开关指向颠倒问题

### ISSUE THREAD

**Issue by lidongcheng88** [fast-crud/fast-crud#179]
![image](https://user-images.githubusercontent.com/45726708/230575139-3e97d0b1-bf61-45fa-bbd3-88021b40f87f.png)
![image](https://user-images.githubusercontent.com/45726708/230574125-f37041b4-fec9-4056-b8ff-1f8b075a7a43.png)
switch 组件这样配置的时候，是和否是颠倒的，目前在 element-plus 遇到，老版本也有这个问题
我需要像这样配一下才行
![image](https://user-images.githubusercontent.com/45726708/230575385-e4bace1f-1d9b-42f4-935f-379180201aa9.png)
![image](https://user-images.githubusercontent.com/45726708/230575457-e31c28e6-7a2f-4c55-96d7-b7a2d41f825f.png)

**Comment by greper** [comment]
dict-switch里面默认是第一个选项为是的样式，第二个选项为否的样式。
你需要将此处交换一下位置
![image](https://user-images.githubusercontent.com/1687298/230576615-ed034710-8097-49a4-9dc2-1d6ad282e39d.png)

**Comment by lidongcheng88** [comment]
哦哦好的
