### ISSUE TITLE
0.17.x BUG反馈

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#18]
## 本地没问题，打包后编辑的时候 未操作文件控件 点保存提示如下
![image](https://user-images.githubusercontent.com/13896536/129134811-732dcff1-e853-4899-bbb2-98567619f737.png)

![image](https://user-images.githubusercontent.com/13896536/129134873-8df0a529-bd69-449f-b14a-b0e6d5cbf5dc.png)

**Comment by levin950825** [comment]
![image](https://user-images.githubusercontent.com/13896536/129139634-2ff6106e-26dd-4ced-a7e6-54fa4188b0b2.png)

http://fast-crud.docmirror.cn/antdv/#/crud/component/uploader/qinius演示地址也有此问问题

**Comment by greper** [comment]
0.17.4 已修复
