### ISSUE TITLE
图片上传提交BUG

### ISSUE THREAD

**Issue by liaojinlong** [fast-crud/fast-crud#180]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
图片上传完毕，点提交就出现：还有文件正在上传，请等待上传完成，或删除它
1.11.10没问题，1.13.0 有问题

### 复现步骤
上传完图片，点确定。必定会提示：还有文件正在上传，请等待上传完成，或删除它

### 代码截图
![image](https://user-images.githubusercontent.com/17539768/230782329-c70b3e7d-e5b1-400d-b34a-34fad441e162.png)

### 报错截图
![image](https://user-images.githubusercontent.com/17539768/230782304-fbb10116-05da-471c-8db7-b4223cc30d94.png)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`请注明`

**Comment by liaojinlong** [comment]
![image](https://user-images.githubusercontent.com/17539768/230808630-83f2eb3b-0647-4ae9-8229-3d5b734daeb0.png)
加了这个不校验就不会提示··它变成默认就去校验了··而且肯定是有问题的···

**Comment by greper** [comment]
1.13.1 已修复
