### ISSUE TITLE
FastCrud 去除输入框前后空格或者校验空格输入的快捷功能，希望能更新上去

### ISSUE THREAD

**Issue by fengrongkai** [fast-crud/fast-crud#182]
FastCrud 去除输入框前后空格或者校验空格输入的快捷功能，希望能更新上去，
1.问题原因：在输入空格时保存，需要校验，一个个加工作量就比较大

**Comment by fengrongkai** [comment]
希望有输入框 trim()修饰符的配置

**Comment by greper** [comment]
可以考虑自定义字段类型，或者修改官方text字段类型
http://fast-crud.docmirror.cn/guide/advance/column-type.html#添加自定义字段类型

**Comment by greper** [comment]
已支持
http://fast-crud.docmirror.cn/antdv/#/crud/component/text
参考示例
