### ISSUE TITLE
bug:文件上传的类型限制不起作用

### ISSUE THREAD

**Issue by wanpong007** [fast-crud/fast-crud#184]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`在使用表单本地上传功能时，限制 类型的上传不生效，示例上只能上传jpg，但我上传pdf也是可以的

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
![image](https://user-images.githubusercontent.com/9105472/231410365-4e9a0b0c-5c38-472f-b391-3126cfe02b74.png)

### 报错截图
![image](https://user-images.githubusercontent.com/9105472/231410344-8bec7255-5372-4df7-87d4-39cf97e564f6.png)

### 效果截图
![image](https://user-images.githubusercontent.com/9105472/231410379-cbccd93f-4e25-4b4c-9bd7-87b50bd4dbcd.png)
#### 1. 期望效果
希望示例上限制类型写了只能传jpg等图片时不能tftfrtfrc选择pdf
#### 2. 实际效果
实际 上现在可以选择pdf

### 1. fast-crud版本：
last
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
配置component.accept:'.png,.jpg'   //注意没有*号
