### ISSUE TITLE
image-uploader等类型在table里面图片加载失败img大小问题

### ISSUE THREAD

**Issue by liaojinlong** [fast-crud/fast-crud#185]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
默认table里面的图片展示有点小，想展示大点的，就在 component 里面定义了 style: 'width:xxxx,height:xxxx'，但是加载失败的图片你们是通过 fs-image-slot 来生成的一个有行内样式的 img，写死的是 max-width:50%
但是这样就会导致成功的图片和失败的图片加载出来大小不一致

### 代码截图
![image](https://user-images.githubusercontent.com/17539768/231624086-8848128c-ee09-4a96-ab32-c291ba8b36bd.png)

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
如果自己定义了 style, 报错的图片应该和自定义的style一致
#### 2. 实际效果
![image](https://user-images.githubusercontent.com/17539768/231624330-278e1d56-e364-431b-ba0a-f81f6af73be7.png)
![5cb51f48d24698886714b5b3ec88277](https://user-images.githubusercontent.com/17539768/231624358-a9dbd839-1c64-47af-a405-43a9848de433.png)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：ruoyi

**Comment by greper** [comment]
已支持
