### ISSUE TITLE
dic-select column valueBuilder后样式显示问题

### ISSUE THREAD

**Issue by liaojinlong** [fast-crud/fast-crud#187]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
type 为 dic-select ，form里面 valueBuilder 之后  table 里面样式显示有问题（多个tab挤在一起了）

antdv 文档示例没问题   http://fast-crud.docmirror.cn/antdv/#/crud/feature/value-builder
element 文档示例有问题 http://fast-crud.docmirror.cn/element/#/crud/feature/value-builder

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
![image](https://user-images.githubusercontent.com/17539768/232664142-d86fe3e7-58d0-49be-85f2-4d1da7d2c77a.png)
![image](https://user-images.githubusercontent.com/17539768/232664143-bc7badb9-4963-4456-995f-2f2038555482.png)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![image](https://user-images.githubusercontent.com/17539768/232664244-c9cf5d40-5965-4b72-a380-f28cb7773fb4.png)

#### 2. 实际效果

![image](https://user-images.githubusercontent.com/17539768/232664312-f1061fc3-53c6-4049-9d7c-f92f8e32eaf8.png)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
已修复
