### ISSUE TITLE
useFormWrapper方式打开的弹窗以及弹窗内的组件颜色主题没能被全局主题覆盖掉

### ISSUE THREAD

**Issue by NewYouth123** [fast-crud/fast-crud#189]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`useFormWrapper方式打开自定义的弹窗嵌套的fs-crud组件发现主题颜色没正确覆盖`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`
![image](https://user-images.githubusercontent.com/44632617/233596917-cd420e22-c7a1-4951-8e86-3556c2c82aa3.png)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
弹窗内的主题色应当和admin主题色一致
#### 2. 实际效果
![image](https://user-images.githubusercontent.com/44632617/233597986-230ed6b5-641f-403f-9edd-a55723d0fefa.png)

### 1. fast-crud版本：
`请您填写fast-crud的版本  1.13.1`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [x] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.13.5已修复
