### ISSUE TITLE
功能支持：增删改查的ElNotification提示

### ISSUE THREAD

**Issue by H0nGzA1** [fast-crud/fast-crud#190]
功能支持：crud表格新增，编辑时，可配置提示信息，目前只有删除有
<img width="409" alt="image" src="https://user-images.githubusercontent.com/21973212/233631455-433ed057-d8d9-4f64-a5e8-bdbc5a8e7300.png">

**Comment by greper** [comment]
配置form.afterSubmit自行实现吧
http://fast-crud.docmirror.cn/api/crud-options/form.html#aftersubmit
