### ISSUE TITLE
好像类型提示我没有安装上

### ISSUE THREAD

**Issue by 1229984599** [fast-crud/fast-crud#192]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`项目启动时一直会提示这个，另外大佬有兴趣把pure-admin也加入进来吗`
![image](https://user-images.githubusercontent.com/34052312/234031028-5b7d2f15-7eb4-49e8-8313-b7a32c7e9fc0.png)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [ x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`pure-admin`

**Comment by greper** [comment]
import 类型的时候只需要@fast-crud/fast-crud即可，不需要dist后面那一串
