### ISSUE TITLE
操作列设置时，本地字典渲染失效

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#194]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述

随便勾选一个列保存，然后会看到本地字典渲染失效。
![image](https://user-images.githubusercontent.com/13896536/236611166-fd1b53b3-9ecd-46f0-acdf-6b9c6bb13020.png)

### 复现步骤

随便勾选一个列保存，然后会看到本地字典渲染失效。

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
无错误日志

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [x] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.13.5已修复
