### ISSUE TITLE
希望开发一个 按钮 不用显示table数据 只想要表单 【需求】

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#20]

**Comment by greper** [comment]
自定义表单支持crudOptions配置构建formOptions
http://fast-crud.docmirror.cn/antdv/#/crud/form/custom-form
http://fast-crud.docmirror.cn/antdv/#/crud/form/independent


新页面打开表单
http://fast-crud.docmirror.cn/antdv/#/crud/form/new-page
