### ISSUE TITLE
antdv 4.0 问题

### ISSUE THREAD

**Issue by Zz1204** [fast-crud/fast-crud#211]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述

1、配合antdv 4.0使用，控制台报错，antdv modal drawer组件的API有变更；
2、列设置配置多选框全选状态有问题；

### 复现步骤
[👉codesandbox代码](https://codesandbox.io/s/objective-jones-yhn49s?file=/src/components/HelloWorld.vue)

### 报错截图
1、控制台报错截图
![控制台报错截图](https://github.com/fast-crud/fast-crud/assets/34231460/4675a9ca-3ca2-43f8-b1f4-dfce3887973b)

2、列配置多选框全选状态
![image](https://github.com/fast-crud/fast-crud/assets/34231460/6202eecb-7686-48bd-8289-526d9b529a82)
![image](https://github.com/fast-crud/fast-crud/assets/34231460/cfe8193e-7c12-45ea-a9cb-259f387d57d8)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by Zz1204** [comment]
补充下操作方式，有点糊
![无标题视频 - Made with Clipchamp](https://github.com/fast-crud/fast-crud/assets/34231460/47035e01-832b-4bf8-8ed2-ef9bd9f8f5cd)

**Comment by greper** [comment]
1.16.0 已支持
http://fast-crud.docmirror.cn/antdv4/
