### ISSUE TITLE
希望Fs-table能独立使用

### ISSUE THREAD

**Issue by husky-dot** [fast-crud/fast-crud#214]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

### 复现步骤

希望Fs-table能独立使用
场景： fs-search 隐藏掉，自己自定义样式布局，然后只使用 fs-table的能力。搜索框同步searchform给crudbinding
doSearch的时候从crudbinding取searchform

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.6.0 已支持，crudOptions.search.validatedForm 不再依赖于fs-search组件。 直接修改即可让doRefresh方法执行查询条件
