### ISSUE TITLE
tab点击查询问题

### ISSUE THREAD

**Issue by liaojinlong** [fast-crud/fast-crud#215]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
点击tab查询不会把search表单的值传到pageRequest里，并且会清空search的内容

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![d36c5967978b2ec37c362a91619b8d2](https://github.com/fast-crud/fast-crud/assets/17539768/84a91541-fb2a-4f65-92a3-8611b4a8ceef)
![9b6f87b3386104caff0827e15d4b48d](https://github.com/fast-crud/fast-crud/assets/17539768/21149533-72e1-4675-a6ac-84fd01c4bf13)
#### 2. 实际效果
![b0d050839dac45213b55362002da685](https://github.com/fast-crud/fast-crud/assets/17539768/b9b6b625-ea9e-424d-9638-ca308e0a02f5)
![67465a52978b3348aa39fcfcb341b46](https://github.com/fast-crud/fast-crud/assets/17539768/4300692c-82a8-4c02-8c9f-3c4667669657)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`请注明`

**Comment by greper** [comment]
1.6.0 已修复
