### ISSUE TITLE
antdv4中，日期时间范围组件设置默认值会报错

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#217]
## 一、问题描述
升级到antdv v4.0.0后，fast-crud及相关包使用 1.13.8、1.15.1、1.16.0，都会出现，给 `datetimerange` 类型的字段设置默认值，点击该组件，控制台报错

### 代码截图
```
// 设置默认值 
function defaultTimeRange(start = 6, end = 0) {
  const startTime = dayjs().subtract(start, 'day')
    .startOf('day')
  const endTime = dayjs().subtract(end, 'day')
    .endOf('day')
  return [startTime, endTime]
}
```

```
search: {  
        initialForm: {
          timeRange: defaultTimeRange(29), // 设置默认值
        },
      }
timeRange: { // 字段设置
          title: '时间',
          type: 'datetimerange',
          search: { show: true },
          column: { show: false, columnSetShow: false },
        }
```

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/5880014/99c7df37-f952-423a-9b12-0046a8deae80)

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.16.0",
    "@fast-crud/ui-antdv": "^1.16.0",
    "@fast-crud/ui-antdv4": "^1.16.0",
    "@fast-crud/ui-interface": "^1.16.0",

### 2. 使用的ui库以及版本
- [x] Antdv (4.0.0)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
dayjs版本问题
