### ISSUE TITLE
【需求】搜索组件添加展开功能

### ISSUE THREAD

**Issue by sunshio** [fast-crud/fast-crud#22]
【需求】搜索组件添加展开功能
![image](https://user-images.githubusercontent.com/38320937/135020419-4516a858-977a-4f47-9534-80579aaa699f.png)
![image](https://user-images.githubusercontent.com/38320937/135020458-c1f4ec5f-27d8-4a6b-96a1-6426f2941861.png)

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/antdv/#/crud/feature/search-multi
