### ISSUE TITLE
fs-button组件的text字段和naive-ui的button的text字段冲突

### ISSUE THREAD

**Issue by yangpeng96** [fast-crud/fast-crud#221]
## 一、问题描述
fs-button组件的text字段和naive-ui的button的text字段冲突
导致naive-ui中button的原生text效果不生效：是否显示为文本按钮

### 代码截图
fs-button的属性
![image](https://github.com/fast-crud/fast-crud/assets/28601423/99e7ece4-5924-4ede-a0c0-822836ccc4e8)

naive ui的button
![image](https://github.com/fast-crud/fast-crud/assets/28601423/a0a5e2e2-1d56-40db-bb4e-b0aefa835c71)

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![image](https://github.com/fast-crud/fast-crud/assets/28601423/8c912d55-f7bb-4d74-8fc5-de6dfe079af5)

#### 2. 实际效果
![image](https://github.com/fast-crud/fast-crud/assets/28601423/960253d8-5289-4145-b276-177f91d2ae3b)

### 1. fast-crud版本：
1.16.2
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [x] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.16.5已修复  配置 buttonProps.text=true即可
