### ISSUE TITLE
initialForm会覆盖view和edit的数据

### ISSUE THREAD

**Issue by IanMua** [fast-crud/fast-crud#222]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
我想要实现initialForm可以在add时给表单初始值，但是在view和edit获取到值的情况下，依旧会覆盖值

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`
`export default function ({ expose, context }) {
	const api = new SysCommonContent();
	const { rechargeActivityRulesListRef } = context;
	console.log("crud context -----------------", rechargeActivityRulesListRef);
	const pageRequest = async (query) => {
		const result = await api.page(query);
		parsePageInfo(expose, result);
		return result;
	};
	const editRequest = async ({ form, row }) => {
		form.id = row.id;
		addParseInfo(expose, form);
		return await api.update(form);
	};
	const delRequest = async ({ row }) => {
		return await api.delete({ ids: [row.id] });
	};
	const addRequest = async ({ form }) => {
		console.log("提交查看----------", form);
		addParseInfo(expose, form);
		return await api.add(form);
	};
	const selectedIds = ref([]);
	const onSelectionChange = (changed) => {
		selectedIds.value = changed.map((item) => item.id);
	};
	return {
		selectedIds,
		crudOptions: {
			request: {
				pageRequest,
				addRequest,
				editRequest,
				delRequest
			},
			rowHandle: {
				align: "center"
			},
			form: {
				wrapper: {
					is: "el-drawer",
					size: "50%" //抽屉宽度50%
				},
				labelWidth: "120px",
				initialForm: {
					rechargeActivityRulesList: [
						{
							id: 0,
							activityId: 0,
							conditionalAmount: 0,
							giftAmount: 0
						}
					],
					rechargeActivityFixedAmountList: [
						{
							id: 0,
							activityId: 0,
							amount: 0,
							tag: ""
						},
						{
							id: 0,
							activityId: 0,
							amount: 0,
							tag: ""
						},
						{
							id: 0,
							activityId: 0,
							amount: 0,
							tag: ""
						},
						{
							id: 0,
							activityId: 0,
							amount: 0,
							tag: ""
						},
						{
							id: 0,
							activityId: 0,
							amount: 0,
							tag: ""
						},
						{
							id: 0,
							activityId: 0,
							amount: 0,
							tag: ""
						}
					]
				}
			},`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
这是把initialForm注释掉之后的页面
![image](https://github.com/fast-crud/fast-crud/assets/91775233/782beec1-0c18-4970-8576-b735b44ac229)

#### 2. 实际效果
![image](https://github.com/fast-crud/fast-crud/assets/91775233/73316a1b-2b5d-44ea-ba66-7dcdaec09fc0)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x] ElementPlus（1.5.0）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.16.5已修复
