### ISSUE TITLE
order排序和editable无法正常工作

### ISSUE THREAD

**Issue by 1229984599** [fast-crud/fast-crud#223]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
1. CommonOptions配置中我设置了`create_time`排序到最后，但是实际使用时它还是会出现在最前面。（已尝试将`order`设置为1000，还是没有反应）
![9416702f74dd13f8455aaf9dcadf5962](https://github.com/fast-crud/fast-crud/assets/34052312/0857ffdf-c786-41a7-8b5a-5fef55dcb007)
2. table中如果是树形结构，只有没有父类的节点才能编辑
![4ee5e8dbed7eecccb8103d487adeaec4](https://github.com/fast-crud/fast-crud/assets/34052312/8cc9092e-581a-40b8-a1ff-dbb534d846b2)

### 1. fast-crud版本：
`1.16.2`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（2.3.9）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`自己搭建`

**Comment by greper** [comment]
1.16.7  字段排序 已修复
