### ISSUE TITLE
【bug】搜索及重置时，不会恢复默认page信息

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#224]
## 一、问题描述
升级到1.16.6包，搜索及重置时，不会恢复默认page信息。
1. 如，每页调整为20条，并切换到第2页后，点击「重置」，仍停留在第二页，pageNum仍是2，pageSize仍是20，未恢复默认的pageNum=2 , pageSize=10。这时候输入一个查询条件，点击「查询」，pageNum还是2，不是1，导致结果少于20条时，提示无数据

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/5880014/f7fd9273-6194-4008-b135-a1f33d5fff11)

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.16.6",
    "@fast-crud/ui-antdv": "^1.16.6",
    "@fast-crud/ui-antdv4": "^1.16.6",
    "@fast-crud/ui-interface": "^1.16.6",

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv ("ant-design-vue": "^4.0.0",)
### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
1.16.7 已修复
