### ISSUE TITLE
是否能将form.wrapper纳入compute上下文范围

### ISSUE THREAD

**Issue by lazervlad** [fast-crud/fast-crud#225]
## 一、问题描述
是否能将form.wrapper纳入compute上下文范围

### 1. fast-crud版本：
1.13.6
### 2. 使用的ui库以及版本
- [] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x ] NaiveUI（2.34.4）

`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [x ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
wrapper.buttons已纳入compute上下文范围，其他的不太好弄，如果有需求请另外提issue
