### ISSUE TITLE
功能需求:form组件可以单独使用

### ISSUE THREAD

**Issue by timeroar** [fast-crud/fast-crud#226]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
请求新功能: form表单的组件比如上传组件可以单独使用

### 1. fast-crud版本：
`请您填写fast-crud的版本`
1.14.7
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（2.34.4）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`自研`

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/antdv/#/crud/form/independent

示例在这里

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/naive/#/crud/component/independent
