### ISSUE TITLE
国际化 情况下 表单 中英文label 长度不一致导致的样式异常 示例添加

### ISSUE THREAD

**Issue by AaronWang3369** [fast-crud/fast-crud#230]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、国际化 情况下 表单 中英文label 长度不一致导致的样式异常 示例添加
在中文情况下样式是正常的
![image](https://github.com/fast-crud/fast-crud/assets/16057795/ef20768b-3913-40fd-9449-82b96fe04136)

当切换为英文的时候由于英文过长导致样式发生异常
![image](https://github.com/fast-crud/fast-crud/assets/16057795/4af17559-e032-429d-9ecf-dee70ca084ed)

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/antdv4/#/crud/form/base   
此处演示调整labelWidth
![image](https://github.com/fast-crud/fast-crud/assets/1687298/d2763b4d-db4b-4262-bd48-e422704a99f9)
