### ISSUE TITLE
数据是含children的数据结构，在配置了valueBuilder转换后，点击子集的编辑按钮无法生效。

### ISSUE THREAD

**Issue by zhx1990** [fast-crud/fast-crud#231]
使用fs-crud版本： 1.14.7
配置如下：
searchDate: {
          title: '资料截止日期',
          type: 'datetime',
          valueBuilder(context) {
            const { value, row, key } = context
            if (value) {
              row[key] = dayjs(value).valueOf()
            }
          },
          valueResolve(context) {
            const { value, form, key } = context
            if (value) {
              form[key] = value.map((item) => dayjs(item).format('YYYY-MM-DD HH:mm:ss'))
            }
          },
        }

数据结构如下：
list: [
    {
      key: 0,
      c: '1187',
      d: '1171755',
      e: '258000',
      f: '76869',
      g: '304120',
      searchDate: '2014-04-16 00:00:00',
      children: [
        {
          key: 1,
          c: '63.6',
          d: '20519',
          e: '36961',
          f: '9917',
          g: '38788',
          searchDate: '2014-04-16 00:00:00',
        },
      ],
    },
  ],

**Comment by greper** [comment]
1.16.8 已支持
