### ISSUE TITLE
[bug]最新版本，点击重置按钮时不会重置sort排序内容

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#234]
## 一、问题描述
在使用`V1.16.7` 版本时，
1. 查询支持排序功能，点击「重置」按钮时，其他数据可重置，sort相关数据未重置。
2. 如果实在currentPage=2时，点击可排序的列名，能正常排序，但currentPage未变成1，还是2。

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.16.7",
    "@fast-crud/ui-antdv": "^1.16.7",
    "@fast-crud/ui-antdv4": "^1.16.7",
    "@fast-crud/ui-interface": "^1.16.7",

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv ("ant-design-vue": "^4.0.0",)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
已实现
