### ISSUE TITLE
多语言模式下的优化建议

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#235]
> 多语言模式下的优化建议

## 一、问题描述

已参考 ISSUE https://github.com/fast-crud/fast-crud/issues/230
我看了这个issue 但这样处理会很麻烦    因为一个表单很多字段每个都这样处理工作量就会大很多了
而且分辨率不同的情况下  设置固定px 局限性就更大了，虽然可以写样式处理但是相应的工作量会增加不少 
是否可以支持下【超出换行】 和 【超出隐藏 鼠标悬浮显示】【标题放上面】 三种模式

### 代码截图
<img width="978" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/df86578d-4e38-4a7d-84b6-138094ff6f2b">

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by levin950825** [comment]
还有一种方案就是 【标题放上面】  
<img width="1878" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/d3023b04-2a1d-44b3-95d7-fcffa63d3e54">

**Comment by greper** [comment]
1.17.0已实现 默认超出隐藏+鼠标悬浮显示， 可以选择配置label上置
label上置示例
http://fast-crud.docmirror.cn/antdv4/#/crud/form/base
