### ISSUE TITLE
fast-curd的element-plus表格

### ISSUE THREAD

**Issue by l1518501871** [fast-crud/fast-crud#236]
请求添加一个 el-table表格树形懒加载的示例。这是我自己做的配置，出现的问题：修改子项时，表格刷新，但是子项数据不是最新数据。（怎么在更新子项的时候，让子项回显最新的数据）

![I%C5M~8A5%L`9)UDBN1@){L](https://github.com/fast-crud/fast-crud/assets/102815790/5ab66fd9-9548-471b-a5be-740f1b8d5dd7)

**Comment by greper** [comment]
已实现，请看tree组件示例
