### ISSUE TITLE
table选择框

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#237]
## 一、问题描述
<img width="1207" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/5e1f4839-097b-4165-9a90-7984870d7db7">
实际企业开发中很常见弹窗选择，以及回显列表查询，期望可以通过fast-crud 内置支持一下简化开发工作

### 代码截图
<img width="1207" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/ebb751ea-5619-44d0-a4e6-29ac87bee515">

#### 1. 期望效果
期望可以通过简单的配置 比如 jsx 或者引入自定义组件完成
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by levin950825** [comment]
可以专门弄个这样的组件  选择回显啥的   里面放jsx 和请求地址  
不然场景多 自己疯狂写弹窗 回显和ref  会很麻烦  期待内置组件支持

**Comment by greper** [comment]
1.17.0已支持
