### ISSUE TITLE
naiviUI下 查询框布局拥挤

### ISSUE THREAD

**Issue by timeroar** [fast-crud/fast-crud#238]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
naiviUI下 查询框布局拥挤

### 代码截图
![1694486021025](https://github.com/fast-crud/fast-crud/assets/37179977/8075fb9d-2c83-463b-960f-58e5e14e0c1c)

### 效果截图
![1694485996347](https://github.com/fast-crud/fast-crud/assets/37179977/a164d6d6-a3c6-4858-837c-bbc9f39853c7)

#### 1. 期望效果
查询框可以自适应
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`自研`

**Comment by greper** [comment]
1.17.0做了一点小优化，看看是否合适，如果还是很拥挤，请重新提交issue
