### ISSUE TITLE
table-select 优化建议

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#241]
## 一、问题描述

选择一行 的完整数据可以使用   有时候不仅仅需要label   一行里面 名称手机号都需要存储 这个就不好实现了  
反显可以只显示label  或者显示全部   这样灵活一些  很多时候都是为了冗余数据的
一般选择一行 可能拿1个或者多个 目的是为了冗余数据
但是回显的时候这数据可能就有了  所以通过配置让开发者自行决定
自定义回显的话 后端通常是会返回的     如果不配置 那么就通过映射关系 自动从字典关联出来

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.17.2已支持
