### ISSUE TITLE
搜索栏配置labelPostion为top无效

### ISSUE THREAD

**Issue by zsbugs** [fast-crud/fast-crud#243]
## 一、问题描述
搜索栏配置labelPostion为top无效，但配置为left和right成功

### 复现步骤
search: {
        show: true,
        options:{
          labelPosition:'top',
          inline:false
        }

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/44670189/bcb15942-6e72-444b-bd94-bfbbd2e9af37)

### 1. fast-crud版本：
 "version": "1.13.2",
### 2. 使用的ui库以及版本
 "element-plus": "^2.3.0",

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.17.2已支持  http://fast-crud.docmirror.cn/element/#/crud/feature/search
