### ISSUE TITLE
naive ui 用uploader上传多个图片后，删除全部上传图片，界面显示为空，但是js绑定数据中还有一条数据

### ISSUE THREAD

**Issue by ly2698127913** [fast-crud/fast-crud#244]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

用uploader上传多个图片后，删除全部上传图片，界面显示为空，但是js绑定数据中还有一条数据

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

![image](https://github.com/fast-crud/fast-crud/assets/48972773/f06b5b21-0930-4886-9b07-1ad036fc2ec5)
![image](https://github.com/fast-crud/fast-crud/assets/48972773/77680809-8f52-453a-8145-5cb0be6eb933)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`

1.17.0

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`

NaiveUI（版本号： 2.34.4 ）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
fs-admin-naive

**Comment by greper** [comment]
1.17.2已修复
