### ISSUE TITLE
富文本编辑器图片上传无法使用

### ISSUE THREAD

**Issue by timeroar** [fast-crud/fast-crud#245]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
fileUploader配置了form上传方式 但是报错没有upload方法

### 代码截图
![({IA(GG93MJT8QU~958UDMK](https://github.com/fast-crud/fast-crud/assets/37179977/86077baa-304a-4dbe-b077-42f48cec8801)
![DPHQ ~DH6DZ{@E %U~~9MJ7](https://github.com/fast-crud/fast-crud/assets/37179977/d3cae5df-76da-40ba-af79-464b86bd3c43)
![RS1RL(UHXZMO}PK2BN(UQE](https://github.com/fast-crud/fast-crud/assets/37179977/99e97e91-b818-472a-8885-1aaf114d7573)

### 报错截图
![O)5B631IT0YG7G_`GWB4O%F](https://github.com/fast-crud/fast-crud/assets/37179977/fc0a405b-bfcb-4f1d-aed7-507571b19918)

#### 1. 期望效果
正常上传图片视频

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`自研`

**Comment by greper** [comment]
1.17.2 已修复
