### ISSUE TITLE
dict 单例全局缓存失效

### ISSUE THREAD

**Issue by VXenomac** [fast-crud/fast-crud#246]
## 一、问题描述
dict 全局缓存单例也应该有效才对，但现在依然会进行后端请求

### 1. fast-crud版本：
`^1.13.6`
### 2. 使用的ui库以及版本
- [x] NaiveUI（2.34.4）

### 3. 使用的admin框架
- [x] fs-admin-naive

**Comment by greper** [comment]
本地测试 缓存有效，没有复现bug
