### ISSUE TITLE
关闭对话框，调用onClosed方法生效问题

### ISSUE THREAD

**Issue by GuobaoCui** [fast-crud/fast-crud#248]
## 一、问题描述
独立使用表单-打开对话框-关闭对话框，调用onClosed方法未生效

### 复现步骤
独立使用表单-打开对话框-关闭对话框

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/64345558/7b9f2da3-976e-4e96-a4b6-1b3f2bf44635)

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/64345558/69328566-39b9-44eb-aee1-4ab017d4efac)

#### 1. 期望效果
关闭弹出框，调用onClosed方法

#### 2. 实际效果
关闭弹出框，onClosed方法未进行调用
![image](https://github.com/fast-crud/fast-crud/assets/64345558/ef4d36eb-638c-42c1-90ae-7fce5ad88022)

### 1. fast-crud版本：
1.17.1
### 2. 使用的ui库以及版本
NaiveUI

### 3. 使用的admin框架
fs-admin-naive

**Comment by greper** [comment]
1.17.2已修复
