### ISSUE TITLE
建议新增选中行功能

### ISSUE THREAD

**Issue by H0nGzA1** [fast-crud/fast-crud#250]
<img width="917" alt="image" src="https://github.com/fast-crud/fast-crud/assets/21973212/c4d9e6aa-26a5-4986-81a5-71e8362909c2">

建议内置选中行功能，无需再手写选择逻辑

**Comment by levin950825** [comment]
支持

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/antdv4/#/crud/basis/plugin

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/api/crud-options/settings.html#plugins
