### ISSUE TITLE
字典颜色渲染优化

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#252]
## 一、问题描述
支持全局开启字典颜色渲染，如果配置了局部的以局部为准，没配置就以全局的支持（这样就不用每个组件开启 color:'auto' 了 ）

#### 1. 期望效果
<img width="957" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/eb0cf28b-bf41-4d23-83eb-e1528fbe1356">

### 1. fast-crud版本：
最新
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/guide/advance/column-type.html#修改官方字段类型配置
