### ISSUE TITLE
最新版本的列配置中valueResolve方法突然失效

### ISSUE THREAD

**Issue by smallchow** [fast-crud/fast-crud#253]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
在升级到fast-crud的最新版本1.17.2后，原来的列配置中的valueResolve方法失效，不管是配置在column key:{valueResolve}中还是 key:{form:{valueResolve}}中，都无法起作用。
如果配置在key:{search:{valueResolve}}字段的search中，是可以生效的，但是不可能再把每个页面的配置重新改一遍了，太多页面了。

### 复现步骤
任何表单提交（包括add，edit，search等）时，需要对字段值进行加工处理后返回后端的，valueResolve方法都不会触发。

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/55643518/cafcdc29-c5fc-4a66-bd40-95f74d092ac8)

### 报错截图
不会报错

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
在表单提交（add,edit,search等）时，希望对字段进行加工处理，比如把数组值变成字符串值。
#### 2. 实际效果
没有触发valueResolve方法，导致后端接收的值有问题

### 1. fast-crud版本：
1.17.2

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？3.2.17)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by jeffrey-bin** [comment]
@greper   你好，这个问题麻烦尽快解决一下哈~

**Comment by greper** [comment]
已将valueResolve 设置为默认复制到search里面
