### ISSUE TITLE
【BUG】缺少监听table组件的expand等事件

### ISSUE THREAD

**Issue by 1014156094** [fast-crud/fast-crud#256]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
![image](https://github.com/fast-crud/fast-crud/assets/16074662/bacf09f8-7cfa-4e2b-8269-d68aad7cb87c)

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x ] 其他：`请注明`

**Comment by greper** [comment]
配置 
```
table:{
        onExpand(open, row) {
          console.log("expand事件：", open, row);
        },
}
```

**Comment by 1014156094** [comment]
文档缺少

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/api/crud-options/table.html
这属于对应组件库的参数，你需要根据对应ui的文档自己去配置
![image](https://github.com/fast-crud/fast-crud/assets/1687298/c6d69e5f-9fd4-48dd-b801-0e8e0816828f)

**Comment by 1014156094** [comment]
噢噢懂了，事件要on开头
