### ISSUE TITLE
fast-file-uploader组件bug

### ISSUE THREAD

**Issue by jj2450465614** [fast-crud/fast-crud#257]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
fast-file-uploader组件，如果给字段赋值为{url:url,key:key}时，会报错e.lastIndexOf is not a function
![PT{6)U83}~LVOIYJW@F4 0B](https://github.com/fast-crud/fast-crud/assets/49241297/5586c191-b59d-4322-b183-4f35ad94b35b)
![PT{6)U83}~LVOIYJW@F4 0B](https://github.com/fast-crud/fast-crud/assets/49241297/7019ccf6-8c8c-4211-ba72-a930746720ad)
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`
### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/49241297/f09b0b80-9ef1-469c-8151-7d5e976024f6)
### 报错截图
![RN6VMRV2 8$(}SK08FM6U0](https://github.com/fast-crud/fast-crud/assets/49241297/0b57e0f6-5ac9-4262-8322-52265e84c2c6)
### 效果截图
`请贴出效果截图`
#### 1. 期望效果
与fast-image-uploader组件一致，可以直接给字段赋值为obj:{url:xxx，key:xxx}
### 1. fast-crud版本：
1.17.2
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）
### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`请注明`

**Comment by greper** [comment]
这是因为你复制一个object对象之后，获取文件名失败
你配置 getFileName 参数，根据object对象返回一个文件名即可

**Comment by greper** [comment]
升级fs到最新版
