### ISSUE TITLE
希望可以把context傳進到commonOptions(props: any)裡面，這樣方便在統一格式方便拿到context內的變量或者函數

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#261]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
希望可以把context傳進到commonOptions(props: any)裡面，這樣方便在統一格式方便拿到context內的變量或者函數

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/39638038/5852e55f-b68e-46a5-8980-ec6677e4fe24)

### 报错截图
目前無法在到commonOptions(props: any)內拿到對應的context

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
希望可以在commonOptions(props: any)內拿到對應的context，從而操作到裡面的函數及變量

### 1. fast-crud版本： 1.17.0
`请您填写fast-crud的版本`1.17.0
### 2. 使用的ui库以及版本1.17.0
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] ElementPlus 1.17.0

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] dvadmin3

**Comment by greper** [comment]
无法复现，目前测试里面就有context

**Comment by greper** [comment]
你可以试试升级fs到最新版
