### ISSUE TITLE
单独使用表单复用crudBinding时无法正常submit

### ISSUE THREAD

**Issue by yuccal** [fast-crud/fast-crud#262]
## 一、问题描述
使用fs-form-wrapper复用crudBinding时，open方法传入addForm或editForm后实际未传入mode，导致无法doSubmit。
重写覆盖doSubmit方法，或手动传入mode后正常，旧版本无此现象。

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/58621578/a64dd546-36e9-4d77-a58b-3c3ee19769bf)
![image](https://github.com/fast-crud/fast-crud/assets/58621578/8a9f31df-5958-4db5-8596-8b50c8150a20)

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/58621578/a228468d-b076-4892-a22a-f8139d12dfd6)

### 1. fast-crud版本：
`1.17.2`
### 2. 使用的ui库以及版本
- [x] ElementPlus `2.3.9`

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-element

**Comment by greper** [comment]
改回默认 mode=add

**Comment by greper** [comment]
升级到1.18.0再试
