### ISSUE TITLE
DoSearchProps 中的 mergeForm 没被使用。

### ISSUE THREAD

**Issue by YeYinhai** [fast-crud/fast-crud#263]
## 一、问题描述
<img width="632" alt="image" src="https://github.com/fast-crud/fast-crud/assets/9876526/b45be5b2-9616-45ee-9e69-e81067844244">
<img width="844" alt="image" src="https://github.com/fast-crud/fast-crud/assets/9876526/e656476e-c0bf-43fa-a8bf-10334a39f86c">

### 代码截图
![673af0235704b859bf35447b3590a278](https://github.com/fast-crud/fast-crud/assets/9876526/fde7b8a5-89cf-4013-9ec2-eca9f5d76b24)
mergeForm没有被使用？是要抛弃吗？还是预留字段？

### 1. fast-crud版本：
`fast-crud：1.17.0`

**Comment by greper** [comment]
1.18.0已修复
