### ISSUE TITLE
table-select  watch 改进

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#264]
## 一、问题描述

但是点击空白处在点回控件  就还是显示id,没有显示名称

### 复现步骤
<img width="1444" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/df97a795-a13e-4a38-8027-4a9eec0c531b">

<img width="1476" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/ddc07de0-505d-4188-b21d-1db4aa8f09b9">

<img width="1359" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/db841d0d-fd63-4596-912e-690311ccca63">

### 1. fast-crud版本：
1.7.3
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by levin950825** [comment]
<img width="845" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/e98a7ad2-909b-44b1-ae1b-eb1338bfef03">

**Comment by greper** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/1687298/439e192c-7dca-44a6-afc6-e0813f0523a3)
测试table-select没有问题，可能是fs-bpmn有问题

**Comment by greper** [comment]
1.18.3已修复
