### ISSUE TITLE
在fs-admin-element中分組tags的檢驗只是對code字段有效，其它字段名稱都不行

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#265]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
https://github.com/fast-crud/fs-admin-element/blob/main/src/views/crud/form/group-tabs/crud.tsx
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`
其它字段名稱都拿不到scope的錯誤

        group: {
          groupType: "tabs", //collapse， tabs
          accordion: false,
          groups: {
            base: {
              slots: {
                label: (scope) => {
                  return (
                    <span style={{ color: scope.hasError ? "red" : "green" }}>
                      <fs-icon icon={"ion:checkmark-circle"} />
                      商品基础
                    </span>
                  );
                }
              },
              icon: "el-icon-goods",
              columns: ["code", "title", "images"]
            },
            price: {
              label: "库存价格",
              icon: "el-icon-price-tag",
              columns: ["store", "price"]
            },
            info: {
              label: "详情",
              collapsed: true, //默认折叠
              icon: "el-icon-warning-outline",
              columns: ["intro", "content"]
            }
### 效果截图
`请贴出效果截图`

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.18.0已修复
