### ISSUE TITLE
【致命BUG】npm run build 后表格的新增按钮不显示

### ISSUE THREAD

**Issue by 1014156094** [fast-crud/fast-crud#266]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
![image](https://github.com/fast-crud/fast-crud/assets/16074662/837d36ff-d15b-41be-8db3-bcc3ceda8e3a)

npm run dev 的时候是正常的
![image](https://github.com/fast-crud/fast-crud/assets/16074662/049cd207-9cd6-4b18-9901-63320c1e86da)

执行 npm run build 后运行dist里面的项目表格的新增按钮不显示
![image](https://github.com/fast-crud/fast-crud/assets/16074662/94d0a99c-4f97-40f3-98cb-01ac79d70796)

经过我反复实验，去掉 `is: 'fs-layout-card'` 则正常。

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
1.17.5
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ x] 其他：`请注明`

**Comment by greper** [comment]
信息太少，需要保留现场看问题，可能跟样式有关，也可能跟浏览器有关，或者是那个账户没有权限

**Comment by 1014156094** [comment]
去掉 is: 'fs-layout-card' 就正常。
