### ISSUE TITLE
fast-crud ui-Interface 未提供 radio-button

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#271]
## 一、问题描述
fast-crud ui-Interface 未提供 radio-button
![image](https://github.com/fast-crud/fast-crud/assets/13896536/c31b5502-0c8a-4e72-8528-a0c53aa0d41a)

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/13896536/fa7d4820-6089-4932-ab0f-963a528158cb)

### 1. fast-crud版本：

1.17.5

### 2. 使用的ui库以及版本

`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.18.0已支持
