### ISSUE TITLE
在外部編輯窗口中，分組tags的情況下，各字段類型的長度不一致。

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#272]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
在外部編輯窗口中，分組tags的情況下，各字段類型的長度不一致。
![image](https://github.com/fast-crud/fast-crud/assets/39638038/0ff1f903-49cc-45a7-9083-31bed1e51aad)
![image](https://github.com/fast-crud/fast-crud/assets/39638038/dee593e4-a803-4cb6-b408-64dbd1356bdb)

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
"@fast-crud/fast-crud": "^1.17.0",
"@fast-crud/fast-extends": "^1.17.0",
"@fast-crud/ui-element": "^1.17.0",
"@fast-crud/ui-interface": "^1.17.0",

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x ] ElementPlus（	"element-plus": "^2.3.14",）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ x] 其他：dvadmin3

**Comment by greper** [comment]
代码怎么写的？

**Comment by wskaudh** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/39638038/303cde0a-a842-4180-8405-7e102c3492c1)
看到在1.18.2版本已經修復了，感謝。
