### ISSUE TITLE
选择联动报错relativeURL.replace is not a function

### ISSUE THREAD

**Issue by haoqibbbb** [fast-crud/fast-crud#280]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
选择联动组件报错，提示relativeURL.replace is not a function

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
		province: {
			title: "省",
			type: "dict-select",
			search: {
			  show: true
			},
			dict: dict({
			  url: "/api/system/area/?level=1",
			  value: 'id',
			  label: 'name',
			  cache: true
			}),
			form: {
			  valueChange({ form, value, getComponentRef }) {
				form.city = undefined; // 将“city”的值置空
				form.county = undefined; // 将“county”的值置空
				if (value) {
				  getComponentRef("city").reloadDict(); // 执行city的select组件的reloadDict()方法，触发“city”重新加载字典
				}
			  }
			}
		  },
		  city: {
			title: "市",
			type: "dict-select",
			search: {
			  show: true
			},
			dict: dict({
			  cache: true,
			  prototype: true,
			  // url() 改成构建url，返回一个url
			  url({ form }) {
				if (form && form.province != null) {
				  // 本数据字典的url是通过前一个select的选项决定的
				  return `/api/system/area/?pcode=${form.province}`;
				}
				return undefined; // 返回undefined 将不加载字典
			  },
			  value: "id"
			}),
			form: {
			  // 注释同上
			  valueChange({ value, form, getComponentRef }) {
				if (value) {
				  form.county = undefined; // 将county的value置空
				  const countySelect = getComponentRef("county");
				  if (form && form.province && form.city) {
					countySelect.reloadDict(); // 重新加载字典项
				  } else {
					countySelect.clearDict(); // 清空选项
				  }
				}
			  }
			}
		  },
		  county: {
			title: "区",
			type: "dict-select",
			search: {
			  show: true
			},
			dict: dict({
				value: 'id',
				label: 'name',
			  cache: true,
			  prototype: true,
			  url({ form }) {
				if (form && form.province != null && form.city != null) {
				  return `/api/system/area/?pcode=${form.city}`;
				}
				return undefined;
			  }
			})
		  }

### 报错截图
![Uploading image.png…]()

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
	"@fast-crud/fast-crud": "^1.14.7",
		"@fast-crud/fast-extends": "^1.14.7",
		"@fast-crud/ui-element": "^1.14.7",
		"@fast-crud/ui-interface": "^1.14.7",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by haoqibbbb** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/148734765/b09ae451-8066-4c90-9813-14dd4961d26b)

**Comment by greper** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/1687298/4d0d2e70-4998-47a7-b581-9d1f81fcebf3)
先检查一下这个地方传过来的url是怎么样的

**Comment by haoqibbbb** [comment]
> ![image](https://user-images.githubusercontent.com/1687298/278183791-4d0d2e70-4998-47a7-b581-9d1f81fcebf3.png) 先检查一下这个地方传过来的url是怎么样的

![image](https://github.com/fast-crud/fast-crud/assets/148734765/8813445a-c6e4-4c45-8aee-557298c8bcc2)
![image](https://github.com/fast-crud/fast-crud/assets/148734765/b3cc2018-9bdb-4d11-8bf2-ebe92b0aa97d)
dayi打印出来是这个

**Comment by greper** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/1687298/6f5080b8-5881-40e7-81d7-dc394c10c6ed)

**Comment by greper** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/1687298/f7e81358-5828-4cab-8c0d-e3e50e6a6ce2)
