### ISSUE TITLE
【BUG】component配置下面的name字段通过compute计算属来显示不同的组件报错了，报了Component is missing template or render function

### ISSUE THREAD

**Issue by wanpong007** [fast-crud/fast-crud#282]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
component配置下面的name字段通过compute计算属来显示不同的组件报错了，报了Component is missing template or render function. 然后这个子组件 就没有显示
如果不用compute，用固定值 到是没问题

### 复现步骤
component配置下面的name字段通过compute计算属来显示不同的组件报错了，报了Component is missing template or render function. 然后这个子组件 就没有显示
如果不用compute，用固定值 到是没问题

### 代码截图
![X%L2AJ23IWLTTUK0`K3Y}LW](https://github.com/fast-crud/fast-crud/assets/9105472/a7517216-0ce8-42a7-bcb6-9d2288e0da6f)
### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/9105472/5c2ac412-1e42-4c64-ab69-920791fcee70)

### 效果截图
![image](https://github.com/fast-crud/fast-crud/assets/9105472/df2566d7-8c70-40bc-9be8-2f8de61a3605)
#### 1. 期望效果
期望可以显示出表单内容
#### 2. 实际效果
实际子组件显示了空白

### 1. fast-crud版本：
@fast-crud/fast-crud": "1.17.5
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [ x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.18.2已修复

**Comment by wanpong007** [comment]
已验证，确实没有问题了，大佬666
