### ISSUE TITLE
column prop formatter类型

### ISSUE THREAD

**Issue by ZhoufangErqiangu** [fast-crud/fast-crud#283]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
在column中指定了type后, 会导致formatter的参数变为row, 而不是scope context

### 复现步骤
在column中指定type为text

### 代码截图

`const curdOption: DynamicallyCrudOptions = {
  columns: {
    foo: {
      title: "Foo",
      type: "textarea",
      column: {
        type: "text",
        formatter(val) {
          /**
           * should be { row: RowType, key: string, value: ValueType }
           *
           * but get RowType
           */
          console.log("value", val);
          return val;
        },
      },
    },
  },
};`

### 1. fast-crud版本：
`1.13.4`
看了一下源码, 现在应该也有这个问题

**Comment by ZhoufangErqiangu** [comment]
#284

**Comment by greper** [comment]
你用的什么ui。antdv还是element？

**Comment by greper** [comment]
如果不是特殊字段，不要设置columns.key.column.type ,设置了就会按照对应的字段进行render，不再走formatter
如果要设置，你也应该按照文档进行设置
antdv 没有type设置
element type相关设置
![image](https://github.com/fast-crud/fast-crud/assets/1687298/2746426f-e9bf-4b4e-9040-3d54cb39672b)

naive type相关设置
![image](https://github.com/fast-crud/fast-crud/assets/1687298/22d54788-0b65-4414-800e-e8fa47cde11d)

以上都没有type:'text'

**Comment by ZhoufangErqiangu** [comment]
懂了，type和formatter是ui组件的prop了，那应该在文档指明这些重名的属性吧

**Comment by greper** [comment]
type没有重名，主要是formatter确实重名了

**Comment by greper** [comment]
没重名的属性太多 不可能全部写出来
