### ISSUE TITLE
在懶加載的情況下，搜索框搜索完內容之后，點擊清除內容，這時懶加載的values會拿到一個""的字符串，從而導致懶加載提示錯誤

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#289]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
在懶加載的情況下，搜索框搜索完內容之后，點擊清除內容，這時懶加載的values會拿到一個""的字符串，從而導致懶加載提示錯誤
現在只能通過if (!values.includes("")) {這個來進行判斷
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`
![image](https://github.com/fast-crud/fast-crud/assets/39638038/68a5ed51-0277-4c22-9761-956a542ccf8c)

### 报错截图
`请贴出报错日志截图`
![image](https://github.com/fast-crud/fast-crud/assets/39638038/0015605b-4d06-4792-b872-82d528f3e26e)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
"@fast-crud/fast-extends": "1.18.3",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [ x] ElementPlus（"element-plus": "2.3.9",）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x ] 其他：dvadmin3

**Comment by greper** [comment]
好像是element的bug

**Comment by wskaudh** [comment]
明白，那當前只能做個判斷先了。if (!values.includes(""))
