### ISSUE TITLE
in-interface button.group 样式不生效

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#290]
## 一、问题描述
fast-crud interface-ui 的样式不生效
![image](https://github.com/fast-crud/fast-crud/assets/13896536/56995f2a-7052-4ea5-8685-701de7c8635b)

手动导入antdv的button生效
<img width="368" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/ac84807b-ab42-434d-8230-11130eb2cc70">
#### 1. 期望效果
用 ui-interface 的方式也可以做到下面的效果
<img width="960" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/2c6a8fbe-1865-48c2-b6d7-c2cdb97c3011">

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
没看出你想期望啥

**Comment by levin950825** [comment]
<img width="211" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/7de493bc-7a8d-4f40-b4a4-328fffab084e">
这是用fast-crud/ui-interface 不生效的地方

**Comment by greper** [comment]
1.18.4已支持
