### ISSUE TITLE
table 表格的列设置显示隐藏报错

### ISSUE THREAD

**Issue by topascend** [fast-crud/fast-crud#291]
column: {
                        resizable: true,
                        //show: true,
                        width: 100,
                        sortable: "custom",
                        show: computed(() => { 
                            return !(roleId == 1 || roleId == 2);
                        }),
                        columnSetShow: computed(() => {
                            return !(roleId ==1 || roleId ==2);
                        }),
                    },
表格起作用,点击列设置时,不起作用,会报错  Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'show'

把 computed 换成 compute的表格不起作用

"@fast-crud/fast-crud": "^1.18.3",
"@fast-crud/fast-extends": "^1.18.3",
"@fast-crud/ui-element": "^1.18.3",
"@fast-crud/ui-interface": "^1.18.3",

**Comment by greper** [comment]
无法复现
