### ISSUE TITLE
NaiveUi 在使用image-upload组件时,预览图片过大

### ISSUE THREAD

**Issue by timeroar** [fast-crud/fast-crud#296]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
NaiveUi 在使用image-upload组件时,预览图片过大

### 复现步骤
form表单使用image-upload,上传图片,预览过大

### 代码截图
![1699407527959](https://github.com/fast-crud/fast-crud/assets/37179977/8a83f662-afc9-486b-8e8a-430517809023)

### 效果截图
![image](https://github.com/fast-crud/fast-crud/assets/37179977/2922f976-12f2-4035-8039-22106e1ef738)

#### 1. 期望效果
正常显示

### 1. fast-crud版本：1.16.7
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x ] 其他：`自搭建`

**Comment by greper** [comment]
1.19.0修复
