### ISSUE TITLE
简单模式下的列设置项显隐和禁用无效

### ISSUE THREAD

**Issue by yuccal** [fast-crud/fast-crud#300]
## 一、问题描述
简单模式下的列设置项显隐和禁用无效

### 复现步骤
列设置在简单模式下切换列显隐和禁用无效，[官方示例](http://fast-crud.docmirror.cn/element/?#/crud/basis/columns-set) 可复现

### 代码截图
普通模式：
![image](https://github.com/fast-crud/fast-crud/assets/58621578/e92accab-fa59-4bed-9a0d-e4eb48af1494)

简单模式：
![image](https://github.com/fast-crud/fast-crud/assets/58621578/696b363a-1bc1-4611-8bc8-41d503c4f255)

### 1. fast-crud版本：
`1.18.0`
### 2. 使用的ui库以及版本
- [x] ElementPlus（版本2.3.9）

### 3. 使用的admin框架
- [x] fs-admin-element

**Comment by greper** [comment]
1.19.0修复
