### ISSUE TITLE
子表格提交至後臺的數據時，可否取消"$editable_id"提交過去后臺，這樣後臺可以不需要再做任何篩選動作直接存儲

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#302]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
子表格提交至後臺的數據時，可否取消"$editable_id"提交過去后臺，這樣後臺可以不需要再做任何篩選動作直接存儲
![image](https://github.com/fast-crud/fast-crud/assets/39638038/d8a8242c-9b6d-48b3-8adf-d17a92d6fb3b)

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`
![image](https://github.com/fast-crud/fast-crud/assets/39638038/a15372d4-0f40-4e6e-a5ff-16aab9f9b207)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ x] 其他：dvadmin3

**Comment by greper** [comment]
升级到1.19.2，然后按照如下配置设置valueResolve
![image](https://github.com/fast-crud/fast-crud/assets/1687298/d8e0daf5-782a-4ff7-97e4-b16b93bc7f83)
