### ISSUE TITLE
带有请求功能的按钮添加loading

### ISSUE THREAD

**Issue by dongyanghe** [fast-crud/fast-crud#306]
> 非常感谢!有劳大哥

## 一、问题描述
表格页查询、表单页保存等这一类型的按钮可以连续快速点击发起多个重复请求

### 复现步骤
快速点击带有请求功能的按钮

### 代码截图
![f9c725234ee0b0c33b6a6500573e856](https://github.com/fast-crud/fast-crud/assets/11970788/19c10182-0b58-4ebd-a25e-8070389c9223)
`

### 报错截图
无

### 1. fast-crud版本：
最新
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
自己给button增加loading的ref即可，查询已添加loading
