### ISSUE TITLE
【需求】希望增加多字段监听，并实时计算的示例

### ISSUE THREAD

**Issue by haoqibbbb** [fast-crud/fast-crud#308]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
多个字段监听，任一字段发生变化，触发监听，并重新计算

### 效果截图
![7B9(TE8WC` GR}GZ7D5UQ7U](https://github.com/fast-crud/fast-crud/assets/148734765/3bf130e9-b286-4546-929c-08901bb2084b)

**Comment by greper** [comment]
已增加 form.watch api
