### ISSUE TITLE
【需求】希望文件上传组件支持多文件同时上传

### ISSUE THREAD

**Issue by VXenomac** [fast-crud/fast-crud#311]
## 一、问题描述
正在使用阿里云 OSS 上传组件，但当前图片只能一张一张上传，无法多选图片同时上传

**Comment by romejiang** [comment]
如果是 Naive UI 可以通过这个参数实现，所以去看具体的上传UI组件的属性就可以实现。

<img width="1138" alt="image" src="https://github.com/fast-crud/fast-crud/assets/1053325/4fb46fe0-f50b-446e-9d8a-0dd1f95808dd">

**Comment by VXenomac** [comment]
使用了 "@fast-crud/fast-extends" 中的 alioss: {}，[示例参考](http://fast-crud.docmirror.cn/naive/#/crud/component/uploader/alioss)，传了 naive ui 组件的参数进去没有作用，看了源代码那部分应该直接用了 `<input>` 标签

**Comment by greper** [comment]
component:{
 multiple:true 
}

即可
