### ISSUE TITLE
component.name使用局部的组件本身会导致每次响应式数据变化时组件重新创建

### ISSUE THREAD

**Issue by muyedeyingxiong** [fast-crud/fast-crud#312]
## 一、问题描述
component.name使用局部的组件本身，响应式数据变化的时候会导致重新mount组件，体验相当不好

### 复现步骤

1. 应用搜索组件或表单组件使用三方组件
2. 且component.name使用组件对象本身，不适用全局注册的组件名
3. 组件绑定的响应式数据变化时，则组件就会重新create，而不是update

### 代码截图
我直接贴我定位的源码中的问题所在：
![屏幕截图 2023-12-08 165500](https://github.com/fast-crud/fast-crud/assets/41033715/442d9640-89cd-4156-8afe-6dc7a893b131)
这是源码中FsSearch内部组件，merge会导致组件对象的深拷贝，fs-component-render在update的时候判断两个对象不是同一个组件，就会重新mount

### 报错截图
不算错误

### 效果截图
效果就是三方select组件，点击时如果动态加载下拉选项，则组件的重建会导致点击没反应，需要再点击以下才行

### 1. fast-crud版本：
1.19.2

### 2. 使用的ui库以及版本
- [x] ElementPlus 2.3.9

### 3. 使用的admin框架
dv3admin

**Comment by greper** [comment]
1.19.3 已修复
