### ISSUE TITLE
bug-独立使用表单

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#313]
## 一、问题描述
独立使用表单的时候存在的BUG ，目前我看演示案例也存在这个问题

### 复现步骤

- 使用日期控件，会发现提示的是英文而不是中文【中文环境】
- 点击保存的时候控制台有错误
- 没有合并  `setup-fast-crud.ts`  里面的公共form配置

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/13896536/22012c92-3368-4f10-b3cd-8fddef65293a)
<img width="796" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/9ffef89e-86e4-43de-a84d-33886d67af8e">

### 报错截图

![image](https://github.com/fast-crud/fast-crud/assets/13896536/24fb2883-1761-40e5-a299-623dc45118ee)

#### 1. 期望效果
保存控制台无异常，并且渲染正确
### 1. fast-crud版本：

1.19.2

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)

### 3. 使用的admin框架
- [x] fs-admin-antdv
- [x] vben-admin

**Comment by levin950825** [comment]
下面的公共配置也没有生效，目前是单独通过代码覆盖的
<img width="820" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/b7463e08-fbb0-446c-927a-87a78afeb00f">


``` shell
export default function ({ calendarValue }) {
  return {
    crudOptions: {
      form: {
        initialForm: {
          date: calendarValue,
        },
        wrapper: { title: "增加日程", width: "45%" },
        doSubmit({ form }: any) {
          console.log("form", form);
          // return {};
        },
        afterSubmit(ctx: any) {
          console.info("form after submit:", ctx);
          // return true;
        },
      },
      columns: {
        time: {
          title: "时间",
          type: "time",
          form: {
            labelCol: { span: 6 },
            rules: [{ required: true, message: "时间不能为空" }],
          },
        },
        desc: {
          title: "日程描述",
          type: ["textarea"],
          form: {
            labelCol: { span: 3 },
            col: { span: 24 },
            rules: [{ required: true, message: "日程描述不能为空" }],
            helper: {
              position: "label",
              tooltip: {
                placement: "topLeft",
              },
              text: "详细填写描述信息,便于不会忘记今天的任务~~~",
            },
          },
        },
      },
    },
  };
}

```

**Comment by greper** [comment]
第一个问题：需要在app.vue使用fs-form-context包裹router-view

**Comment by greper** [comment]
其他问题无法复现

**Comment by levin950825** [comment]
好的，这样已解决
``` vue
<template>
  <ConfigProvider :locale="getAntdLocale" :theme="themeConfig">
    <AppProvider>
      <fs-form-provider>
        <RouterView />
      </fs-form-provider>
    </AppProvider>
  </ConfigProvider>
</template>
```
