### ISSUE TITLE
【需求】希望可以单独使用table-select 

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#315]
## 一、问题描述
想手动打开一个 table-select 然后拿到选中数据
![image](https://github.com/fast-crud/fast-crud/assets/13896536/212a41d6-d2f3-4e9e-8e57-273c043710f9)

### 效果截图
![image](https://github.com/fast-crud/fast-crud/assets/13896536/eb888359-100a-4db3-ae47-a84e3e7d0230)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
1.19.3 已支持
