### ISSUE TITLE
【BUG】- 删除控制台有异常和警告信息

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#318]
## 一、问题描述
删除控制台有异常和警告信息

### 复现步骤
http://fast-crud.docmirror.cn/antdv4/#/crud/basis/first  官网案例点删除

### 报错截图

![image](https://github.com/fast-crud/fast-crud/assets/13896536/9dc7e5eb-79f3-4f1d-b5c7-ecb05f8eeb65)

**Comment by greper** [comment]
没有复现
