### ISSUE TITLE
【BUG】-日期格式化返回值异常

### ISSUE THREAD

**Issue by duanshuo198802** [fast-crud/fast-crud#321]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
日期类型格式化返回值异常，当日期值新增或修改或重新选择时，日期格式化是生效的，但是日期数据不变更时，日期数据格式化是失效的。

### 复现步骤
http://fast-crud.docmirror.cn/element/#/crud/component/date，在组件示例-日期时间中，点击编辑按钮，点击确定，debug提交数据中"format": "2019-09-21T03:11:11.000Z",但是修改格式化中的值时，debug提交的数据为"format": "2019-09-21 11:11:11",此时格式化返回的数据才是正确

### 代码截图

无

### 报错截图

无

### 效果截图
`请贴出效果截图`
#### 1. 期望效果

"format": "2019-09-21 11:11:11"

#### 2. 实际效果

"format": "2019-09-21T03:11:11.000Z"

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

### 4.修改建议
日期时间选择buildDateValue逻辑需要完善
```
 function buildDateValue(scope: ValueBuilderContext) {
    const { row, key, value } = scope;
    if (value != null) {
      if (ui.type === "naive") {
        row[key] = dayjs(value).valueOf();
      } else if (ui.type === "antdv" && ui.version === "4") {
      } else {
        row[key] = dayjs(value);
      }
    }
  }
```

**Comment by greper** [comment]
1.20.0已优化
