### ISSUE TITLE
1.20.0版本配置form的介面所有的字段會出現排序不統一的情況，發現是由table-select字段與其它如input或者dict-select樣式不一致導致的

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#323]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
在tags分組情況下當前form的介面所有的字段會出現排序不統一的情況

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`
![image](https://github.com/fast-crud/fast-crud/assets/39638038/1ba19e27-718d-4411-83c7-285962d4be97)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
1.19.3
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x ] ElementPlus（"element-plus": "^2.3.9",）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x ] 其他：dvadmin3

**Comment by greper** [comment]
无法复现

**Comment by wskaudh** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/39638038/765018a9-93dd-4640-9fb8-7cb6d782dd8d)
如上圖，只要是配置了table-select的字段，他的樣式就跟別的dict-select沒有對齊。
附上兩個字段的代碼如下
				department: {
					title: '部门',
					search: {
						// disabled: true,
						show: true
					},
					type: 'table-select',
					dict: dict({
						isTree: true,
						value: 'id',
						label: 'title',
						getNodesByValues: async (values: any[]) => {
							if (!values.includes("")) {
								return request({
									url: '/api/department/' + "getbyIds/",
									method: "post",
									data: { values }
								}).then((ret: any) => {
									return ret.data;
								});
							}
						},
					}),
					column: {
						minWidth: 150, //最小列宽
					},
					form: {
						rules: [
							// 表单校验规则
							{
								required: true,
								message: '必填项',
							},
						],
						component: {
							rowKey: "id", //element-plus 必传
							createCrudOptions: department,
							filterable: true,
							placeholder: '请选择',
							props: {
								props: {
									value: 'id',
									label: 'title',
								},
							},
						},
					},
				},

而dict-select的代碼只是正常的配置而以，沒有特殊。
