### ISSUE TITLE
在子表行編輯模式下，dict【数据字典】配置URL或者getData情況下，都無法獲取到編輯狀態好的row數據，只能拿到value值

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#324]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
在子表行編輯模式下，dict【数据字典】配置URL或者getData情況下，都無法獲取到編輯狀態好的row數據，只能拿到value值，
希望可以拿到row,這樣做懶加載也可以處理到，聯動選擇的情況下，也可以根據row值進行判斷拼接URL。

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`
![image](https://github.com/fast-crud/fast-crud/assets/39638038/3e799267-fe42-4abd-abae-d1658bd0935a)
![image](https://github.com/fast-crud/fast-crud/assets/39638038/ea5728f7-0b9b-4a8e-8ff0-f343dda8557a)
![image](https://github.com/fast-crud/fast-crud/assets/39638038/a8b59a2f-318f-4f3a-9306-5b522cf04c06)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
		"@fast-crud/fast-crud": "^1.19.3",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x ] ElementPlus（"element-plus": "^2.3.9",）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x ] 其他：`请注明`

**Comment by greper** [comment]
1.20.0 已优化，应该可以获取到了
