### ISSUE TITLE
希望可以在子表行編輯的模式下，點擊編輯按鈕，可以添加一些事件，比如拿到當前的行數據之類的，目前沒有這個功能，導致點編輯時，拿不到當前的行數據

### ISSUE THREAD

**Issue by wskaudh** [fast-crud/fast-crud#327]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
希望可以在子表行編輯的模式下，點擊編輯按鈕，可以添加一些事件，比如拿到當前的行數據之類的，目前沒有這個功能，導致點編輯時，拿不到當前的行數據
![image](https://github.com/fast-crud/fast-crud/assets/39638038/ddce3fda-30c4-4a9e-baec-7a8ae854979a)

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`
        table: {
          editable: {
            enabled: true,
            mode: "row",
希望可以在editable裡面的一些事件，可拿到當前編輯行的數據。
### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [] Antdv (版本？)
- [x ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x ] 其他：dvadmin3

**Comment by greper** [comment]
补充一下需求，我不知道你在什么时候要拿行数据，拿来做什么用
