### ISSUE TITLE
最新下载的示例代码在vue3.4.6下有大量警告

### ISSUE THREAD

**Issue by zsbugs** [fast-crud/fast-crud#331]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
最新下载的示例代码在vue3.4.6下有大量警告

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/44670189/cc878051-17c3-4dd3-a1b2-7f136fc07094)

### 1. fast-crud版本：
"version": "1.19.3",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
-  [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
-  [ ] fs-admin-antdv
-  [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
没有发现这个警告
