### ISSUE TITLE
国际化切换需要刷新页面才会生效

### ISSUE THREAD

**Issue by weikun321688** [fast-crud/fast-crud#337]
## 一、问题描述
国际化切换时，搜索区域以及UI框架部分可以切换。表格以及表单需要刷新页面才能切换

#### 2. 实际效果
![2a5835f394d07ff397dc85f580066b3c](https://github.com/fast-crud/fast-crud/assets/9813274/4581693d-185f-4b9f-bc4d-e55d434de6f4)

### 1. fast-crud版本：
1.19.3
### 2. 使用的ui库以及版本
NaiveUI

### 3. 使用的admin框架
soybean admin

**Comment by jamesleekko** [comment]
所以是怎样解决呢，表单配置里columns下的title使用t('xxxx')这样的写法，组合式api写法下，改变vue-i18n的locale.value，文本不会切换到对应的语言
