### ISSUE TITLE
【bug】valueBuilder在v1.19.3版本中会执行两次

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#340]
## 一、问题描述
在v1.19.3版本中，在curd的字段配置中，对form中某字段进行`valueBuilder`，会执行两次。
但在 v1.13 的版本中，同样的代码，`valueBuilder`只会执行一次

### 复现步骤
```
createTime: {
          title: '创建时间',
          type: 'text',
          form: {
            show: false,
          },
          viewForm: {
            show: true,
            valueBuilder({ value, key, form }: ScopeContext) {
              if (value) {
                console.log('11111 :>> ') // 在1.19.3时，执行两次
                form[key] = formatTimestampToYearHour(value)
              }
            },
          },
        },
```

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/5880014/773a28a8-1cc6-4855-a930-5ea4faf337d8)

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
`valueBuilder`只执行一次，否则，第二次执行可能导致未知的错误。

### 1. fast-crud版本：
1.19.3
### 2. 使用的ui库以及版本
"ant-design-vue": "^4.0.0",

### 3. 使用的admin框架
"@fast-crud/fast-crud": "^1.16.7",
    "@fast-crud/ui-antdv": "^1.16.7",
    "@fast-crud/ui-antdv4": "^1.16.7",
    "@fast-crud/ui-interface": "^1.16.7",

**Comment by greper** [comment]
1.20.0已优化
