### ISSUE TITLE
rowHandle中的按钮点击时如何弹出一个自定义的modal？

### ISSUE THREAD

**Issue by ofirefish** [fast-crud/fast-crud#346]
定义代码如下，拦截view按钮的click事件，但是不知道如何通知主界面，求帮助！
      
    rowHandle: {
        buttons: {
          view: {
            size: "small",
            click: (context) => {
              #查看按钮的点击事件如何通知主界面打开modal？
            }        
          },          
      },

**Comment by greper** [comment]
index.vue
```
modelVisiableRef = ref(false)
useFs({context:{modalVisiableRef}})
```
crud.tsx
```
createCrudOptions({context}){
 ...
rowHandle:{
 buttons:{
 view:{
   click:(){
    modalVisiableRef.value = true
    }
  }
 }
}
....

}
```
