### ISSUE TITLE
editable全局配置后操作栏无法出现查看和编辑按钮

### ISSUE THREAD

**Issue by 1229984599** [fast-crud/fast-crud#349]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`editable全局配置后操作栏无法出现查看和编辑按钮`

### 复现步骤
`editable`设置为`true`时操作栏只有删除按钮，并且无法编辑
```javascript
table: {
          editable: {
            enabled: true,
            mode: "free",
            activeTrigger: "onClick",
            activeDefault: false,
          },
        }
```
![image](https://github.com/fast-crud/fast-crud/assets/34052312/8511fa8a-dfc7-4c97-a032-b0abb259362f)

`editable`设置为`false`时操作栏能够正常显示
```javascript
table: {
          editable: {
            enabled: false,
            mode: "free",
            activeTrigger: "onClick",
            activeDefault: false,
          },
        }
```
![image](https://github.com/fast-crud/fast-crud/assets/34052312/62b58fc9-861a-4b7c-927c-e06ceccdcc1e)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
`editable`设置为`true`时能够正常使用
#### 2. 实际效果
`editable`设置为`true`时无法正常编辑

### 1. fast-crud版本：
`1.19.3`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（2.3.9）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`自写`

**Comment by greper** [comment]
mode:free  必须activeDefault:true 。 如果你想点击单元格激活编辑，你应该使用mode:cell
