### ISSUE TITLE
table-select选中数据后，当前选择显示的是id而不是label，请优化错误提示

### ISSUE THREAD

**Issue by haoqibbbb** [fast-crud/fast-crud#352]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
table-select选中数据后，当前选择显示的是id而不是label，前端报错
![ZBTOKC62V9_YREN( 8GG_PT](https://github.com/fast-crud/fast-crud/assets/148734765/72187fd5-c1e1-4d10-8064-2b12c075ddde)
后端返回的数据，应该是一个列表，如果直接返回一个对象字典就会出现该错误，并且提示不知道哪里出错
建议，优化错误提示，应该返回一个列表

### 代码截图
代码参照示例

### 报错截图
![Uploading WW40A67P`V7)J)R0V(QVLHK.png…]()

### 测试通过代码：
![image](https://github.com/fast-crud/fast-crud/assets/148734765/0cc4ed7d-4492-4318-a92a-1f906d75abe1)

**Comment by greper** [comment]
1.20.0已优化
