### ISSUE TITLE
级联选择任意一项时，无法正常显示

### ISSUE THREAD

**Issue by leishaoxiong** [fast-crud/fast-crud#36]
官网没有案例，按照ele的props.checkStrictly = true #

- 来设置父子节点取消选中关联，从而达到选择任意一级选项的目的。请问一下，zhel这里该怎么写。
![fast](https://user-images.githubusercontent.com/78367271/144696614-ae3e50d7-74fb-48a1-b462-676e074595bd.png)

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/element/#/crud/component/cascader
案例不是你要的效果？
![image](https://user-images.githubusercontent.com/1687298/144700057-2552f3ec-6fca-478f-a217-c9b983a6a95b.png)

**Comment by leishaoxiong** [comment]
这种是多选级联，ele官网的选择任意一项的第一个例子，这里做后台路由，多选就没办法了，有什么方式可以做么，谢谢回答






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 下午2:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fast-crud/fast-crud] 级联选择任意一项时，无法正常显示 (Issue #36)





 
http://fast-crud.docmirror.cn/element/#/crud/component/cascader
 案例不是你要的效果？
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by greper** [comment]
配置multiple: false 应该就行了，如果不能正常显示，请把不能正常显示的效果截图出来，报错日志截图出来

**Comment by greper** [comment]
columns 里面的multiple 也要设置为false

**Comment by leishaoxiong** [comment]
设置之后，原本的文字就会消失，页面不报错，只是报黄色警告










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fast-crud/fast-crud] 级联选择任意一项时，无法正常显示 (Issue #36)





 
columns 里面的multiple 也要设置为false
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leishaoxiong** [comment]
搞定了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fast-crud/fast-crud] 级联选择任意一项时，无法正常显示 (Issue #36)





 
columns 里面的multiple 也要设置为false
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leishaoxiong** [comment]
你好， 我猜测应该是取消关联的时候，需要重新绑定lable和value，然后就可以正常展示了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fast-crud/fast-crud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fast-crud/fast-crud] 级联选择任意一项时，无法正常显示 (Issue #36)





 
columns 里面的multiple 也要设置为false
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
