### ISSUE TITLE
@iconify/vue 无法定制 provider 和 addCollections

### ISSUE THREAD

**Issue by vellengs** [fast-crud/fast-crud#365]
### 1. fast-crud版本：  1.20.0 

由于@iconify/vue 打进了dist 包，导致无法使用 addCollection, addAPIProvider 了。
```
import { addCollection, addAPIProvider } from '@iconify/vue';
```
建议 build 的时候 externals 加上 @iconify/vue

**Comment by vellengs** [comment]
提交了一个 pull request https://github.com/fast-crud/fast-crud/pull/366

**Comment by greper** [comment]
1.20.1已排除@iconify/vue 需要外部安装
