### ISSUE TITLE
希望组件在 install 的时候能传入替换的组件替换默认的实现。

### ISSUE THREAD

**Issue by vellengs** [fast-crud/fast-crud#367]
export const FastCrud = {
  install(app: App, options: FsSetupOptions = {}) {
    if (options.ui) {
      uiContext.set(options.ui);
    }
    const { merge } = useMerge();
    if (options.commonOptions) {
      defaultCrudOptions.commonOptions = options.commonOptions;
    }
    if (options.dictRequest) {
      setDictRequest(options.dictRequest);
    }

    if (options.i18n) {
      i18n.setVueI18n(options.i18n);
    }
    for (const key in components) {
      // 这里给个机会提供替换机制。
      const com = components[key];
      app.component(key, com);
    }

    FsFormWrapper._context = app._context;

    types.install();

    app.config.globalProperties.$fsui = uiContext.get();

    merge(GlobalConfig.logger, options.logger);
    printWarningLogger(options.logger);
  }
};

**Comment by greper** [comment]
1.20.1已支持
