### ISSUE TITLE
子表格编辑组件，子表新增行的value_change有BUG

### ISSUE THREAD

**Issue by haoqibbbb** [fast-crud/fast-crud#368]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
子表格编辑组件，子表新增行的value_change时有个bug
在行内选择dict-select组件选项后，触发的value_change内的value不对，首次选择打印出来显示选择的选项为undifend

### 代码截图
![image](https://github.com/fast-crud/fast-crud/assets/148734765/f3e09f2f-e8e4-4aa3-9a04-5b5a207c7e6b)

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/148734765/1b26bca4-754c-4088-b9f7-e201284ba645)
![image](https://github.com/fast-crud/fast-crud/assets/148734765/b1b41682-ef2f-4e03-a385-d34ef53b54f5)

### 1. fast-crud版本：
1.20.1最新版本

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`

- [ ] ElementPlus

**Comment by greper** [comment]
第二次选择可以？

**Comment by haoqibbbb** [comment]
> 第二次选择可以？

第二次选择实际上是第一次选择的id,以此类推

**Comment by haoqibbbb** [comment]
同样的配置，如果放在form 下就能正常运行，但是放在column下就有问题
以下是正常运行的代码：
![Uploading image.png…]()

**Comment by greper** [comment]
已修复
