### ISSUE TITLE
您好，表格操作栏，单独控制某一行一个按钮的隐藏与显示，是哪个属性可以操作，文档看了很久，没找到

### ISSUE THREAD

**Issue by leishaoxiong** [fast-crud/fast-crud#37]
- [ ] 
![edit](https://user-images.githubusercontent.com/78367271/147425916-5cfb00ed-6509-4066-a3d1-0152dd712784.png)

**Comment by greper** [comment]
这个配置是控制这个按钮是否显示：  rowHandle.edit.show:false

如果要根据行数据判断显隐，需要配合compute
rowHandle.edit.show: compute(context=>{  return context.row.xxx === xxx })
