### ISSUE TITLE
关于字典缓存

### ISSUE THREAD

**Issue by zuihou** [fast-crud/fast-crud#375]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

### 复现步骤
看了你的文档，关于这句话我的理解是可以将 dict({}) 方法抽取到其他的全局文件中使用
```
建议：不开缓存，将dict()创建的实例放到全局文件中导出，相当于store来使用，一样可以实现全局缓存的效果
```
1. 使用图一的代码，字典数据只有在首次进入页面时，会请求后台接口，并正确回显， 但第二次进入页面或F5刷新页面，字典接口都不会请求后台，字典字段也没有回显为label。 
2. 使用图二和图三的代码，字典数据每次刷新页面都会请求后台接口， 并正确回显字典 label

### 代码截图
- 图一
<img width="555" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/66b0ca14-98c9-4993-bb44-304bab738880">
- 图二
<img width="442" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/c1b3bddb-6146-4e3a-80ef-0b79cd810288">
- 图三
<img width="688" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/4db45ca2-f7a9-46d5-a975-602aa71ba6c8">

### 错误截图
使用图一的代码，无法正确回显字典的label ，显示的是 字典的value 。
强行清空浏览器缓存后，首次进入页面的能正确回显1次， 第二次又不行了
<img width="236" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/b65e7108-0521-41eb-8d5f-44c15746edd0">

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ x ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ x ] soybean-admin

**Comment by zuihou** [comment]
问题2： 
```
const GLOBAL_DICT = dict({
  cloneable: false,
  url: '1', 
  custom: DictEnum.APPLICATION_TYPE,
});
```

 一定要配置 url 后才会请求全局的`dictRequest`方法， 感觉有点不合理， 因为可以在dictRequest方法内部设置请求的地址。

若整个系统请求字典的接口都是同一个，调用`dict({})` 方法时，也不能省略url参数，有点多余。

**Comment by greper** [comment]
问题1：能用第二种，就用第二种，  第一种只有在你dict基本不会变的情况下使用，你需要主动去触发更新，dictRef.reload()
问题2：你做系统不可能只有一个dict， 你会有很多很多种dict。

**Comment by greper** [comment]
对于问题二，既然你用custom来作为请求类型的配置，你随便配置个url都行啊

**Comment by zuihou** [comment]
对于问题1， 现有如下需求：

有多个独立的菜单，员工管理、会员管理、账号管理等菜单，每个菜单都有增删改查等页面，都用到了 “性别”这个字典，我希望3个菜单的所有增删改查等页面都用 同一份“性别” ，该怎么写代码呢？

**Comment by greper** [comment]
dict放到一个文件里实例化以后 导出给三个页面使用
