### ISSUE TITLE
样式颜色污染

### ISSUE THREAD

**Issue by vellengs** [fast-crud/fast-crud#384]
fast crud 的样式污染了组件，建议fast crud 不写样式颜色。
如：
https://github.com/fast-crud/fast-crud/blob/main/packages/fast-crud/src/components/crud/fs-table.less

```
  .ant-table-bordered {
    border-bottom: 1px solid #eee;  这里的颜色

    .ant-table-content {
    }
  }

  .fs-current-row {
    background-color: #b0e2ff;  这里颜色

    td {
      background-color: unset;
    }
  }
```

<img width="1429" alt="image" src="https://github.com/fast-crud/fast-crud/assets/5743338/674ee3c6-12a2-40a3-b87b-f4837ca167c8">

**Comment by greper** [comment]
1.21.0已修复
