### ISSUE TITLE
getFileName 方法不支持await

### ISSUE THREAD

**Issue by zuihou** [fast-crud/fast-crud#385]
<img width="914" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/dc239b99-8e6a-4ac9-a6a8-b58721ece865">

**Comment by zuihou** [comment]
另外，最好让getFileName的 入参 传递为`item`或者**更加丰富的参数**，而不仅仅局限于url。

比如： valueType: 'object' 时， 可能参数里面就已经有文件名了

**Comment by greper** [comment]
1.21.0已支持
