### ISSUE TITLE
【cropper-uploader】图片上传较大的时候报错

### ISSUE THREAD

**Issue by aov2005** [fast-crud/fast-crud#390]
https://github.com/fast-crud/fast-crud/blob/68a941126c38c33b0c47f4110c0f3fb3119bcae4/packages/fast-extends/src/uploader/components/fs-cropper.vue#L287

这里是个异步操作，如果图片比较大的时候会报错，应该是canvas卸载了，图片数据还没输出完

![image](https://github.com/fast-crud/fast-crud/assets/6664259/5b656d6a-e099-47a2-8b19-99dc400750a9)
![image](https://github.com/fast-crud/fast-crud/assets/6664259/41ca85f2-53c7-4c57-b710-61d32b11df9d)

**Comment by greper** [comment]
1.21.0已修复
