### ISSUE TITLE
基于navie-ui，关于datetime组件问题

### ISSUE THREAD

**Issue by zuihou** [fast-crud/fast-crud#392]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
<img width="1522" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/2db60b2e-5d27-4ab1-808d-d72b3a3b011f">
在你的官方示例中，有这样一段描述，但实际上naive-ui是支持使用字符串作为输入和输出的，仅需要使用   v-model:formatted-value  即可，n-ui原始代码如下：

```
      <NDatePicker
        v-model:formatted-value="form.dateTime"
        format="yyyy-MM-dd HH:mm:ss"
        value-format="yyyy.MM.dd HH:mm:ss"
        type="datetime"
      />
```

但我在fast-crud中，尝试使用formatted-value属性时，代码如下：

```
format2: {
  title: '显示格式化(提交格式化)',
  type: 'datetime',
  form: {
    component: {
      // 使用formatted-value来获取 格式化之后的值
      vModel: 'formatted-value',
      // 前端显示的格式
      format: 'yyyy年MM月dd日 HH:mm',
      // 后端传过来的值的格式
      valueFormat: 'yyyy-MM-dd HH:mm:ss',
    },
  },
  // 不加 valueBuilder 方法，编辑和查看页面报错
  valueBuilder({ value, row, key }) {
    if (value != null) {
      row[key] = value;
    }
  },
},
```

必须加上 valueBuilder 方法，将 `row[key] = value;` 后，编辑和查看按钮才能正常打开。
 
若注释 valueBuilder 方法，点击新增按钮，填写format2字段的日期后，提交到后台的值是yyyy-MM-dd HH:mm:ss格式，

后台返回yyyy-MM-dd HH:mm:ss格式的值并渲染在table中后， 点击查看或编辑按钮时， format2的值被自动转换为了 时间戳，导致报错， **请问是不是fast-crud内部进行转换的？**

### 代码截图
<img width="1000" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/a15f80d5-d52e-449b-bc4d-cc608331e177">

### 报错截图
不加 `valueBuilder`方法时，点击编辑和查看按钮报错如下： 
<img width="1511" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/720b45e1-030b-4f5f-a528-77ae43acf681">

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [  ] Antdv (版本？)
- [  ] ElementPlus（版本？）
- [x] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [x] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
默认datetime类型 有配置valueBuilder 他会自动将value转换为dayjs，如果你要使用formatted-value 需要覆盖valueBuilder
