### ISSUE TITLE
切换tab标签默认缓存无效，导致切换tab查询参数丢失

### ISSUE THREAD

**Issue by Tany1iver** [fast-crud/fast-crud#394]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
1. 多个tab标签切换 缓存不生效
![输入图片说明](https://foruda.gitee.com/images/1712929459849870044/ff0ec663_1728665.png "屏幕截图")
2. 打开新的标签
![输入图片说明](https://foruda.gitee.com/images/1712929512670945799/7687c3ae_1728665.png "屏幕截图")
3. 切换回原来的标签 查询参数丢失
![输入图片说明](https://foruda.gitee.com/images/1712929551592940418/b028246a_1728665.png "屏幕截图")
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`
![输入图片说明](https://foruda.gitee.com/images/1712929568971025838/6aaa93be_1728665.png "屏幕截图")
### 报错截图
`请贴出报错日志截图`
无
### 效果截图
`请贴出效果截图`
#### 1. 期望效果
有缓存的tab 标签 查询参数不丢

#### 2. 实际效果
查询参数丢失，导致体验下降

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本号:           )
- [x] ElementPlus（版本号：          ）
- [ ] NaiveUI（版本号：               ）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [x] fs-admin-element
- [x] fs-admin-naive
- [x] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by Tany1iver** [comment]
三级路由会有缓存丢失问题 临时可通过这种方式解决
<img width="398" alt="image" src="https://github.com/fast-crud/fast-crud/assets/166840610/05275720-922c-45fc-8b2a-a162997efff1">

**Comment by greper** [comment]
示例已修复
