### ISSUE TITLE
输入框查询，点击清除按钮无法触发查询，实测降到 1.15 版本不会有这个问题，我用的是 element-plus

### ISSUE THREAD

**Issue by lidongcheng88** [fast-crud/fast-crud#396]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/api/crud-options/columns.html#key-search-autosearchtrigger

你还可以，查看字段类型章节，学习修改官方字段 text，将其search.autoSearchTrigger设置为true 让所有的text字段生效

**Comment by lidongcheng88** [comment]
> http://fast-crud.docmirror.cn/api/crud-options/columns.html#key-search-autosearchtrigger
> 
> 你还可以，查看字段类型章节，学习修改官方字段 text，将其search.autoSearchTrigger设置为true 让所有的text字段生效

好嘞，感谢
