### ISSUE TITLE
编辑表单格式化

### ISSUE THREAD

**Issue by leishaoxiong** [fast-crud/fast-crud#40]
- 你好。当我从后段获取了一个值，type:1 ，前端要格式化表单显示，当type：1的时候，select显示为企业，有这个函数没有，目前的格式化是表格的格式化显示，编辑的时候格式化显示，在哪里呢
![001](https://user-images.githubusercontent.com/78367271/148020882-8e23b0fc-4566-41bb-982f-7a595dcca309.png)

**Comment by greper** [comment]
检查列表数据和dict的数据类型，int和字符串不相等

**Comment by leishaoxiong** [comment]
企业何老师是我写死了的，后端的数据只传了type：1&nbsp; ,渲染的时候，点击编辑，就显示为1 了，我想把1直接改变，就像formatter那样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fast-crud/fast-crud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fast-crud/fast-crud] 编辑表单格式化 (Issue #40)





 
检查列表数据和dict的数据类型，int和字符串不相等
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by greper** [comment]
要么改dict的value 要么改后台返回的数据值

要么配置valueBuilder将数据值转化一下,http://fast-crud.docmirror.cn/api/crud-options/columns.html#valuebuilder与valueresolve
