### ISSUE TITLE
组件使用Ref存在性能隐患

### ISSUE THREAD

**Issue by zhzhh7378** [fast-crud/fast-crud#400]
## 一、问题描述
fastCrud的组件引用默认情况下都是`Ref`，建议全部替换成`shallowRef`.避免性能问题。

### 代码截图
<img width="1440" alt="image" src="https://github.com/fast-crud/fast-crud/assets/14539415/0a21f175-2943-408b-b448-8e32e04db873">
<img width="1440" alt="image" src="https://github.com/fast-crud/fast-crud/assets/14539415/b0cd3a1e-ad2d-4b67-9136-651787614096">

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/14539415/c817fbaf-e16a-478a-93a3-444953c62450)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
这个问题并不是FsComponentRender 的ref问题。 而是你局部引用组件使用了ref方式，你应该检查局部组件引用
![image](https://github.com/fast-crud/fast-crud/assets/1687298/55a6299e-15bc-42c9-9bd3-01cbf61d2773)

ps: 新版版已经不需要配置shallowRef， 你也可以升级fs解决此问题
