### ISSUE TITLE
图片上传组件翻转按钮相反

### ISSUE THREAD

**Issue by dongyanghe** [fast-crud/fast-crud#402]
## 一、问题描述
图片上传组件翻转按钮相反了

### 复现步骤

http://fast-crud.docmirror.cn/element/#/crud/component/uploader/cropper
### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
![image](https://github.com/fast-crud/fast-crud/assets/11970788/8c3a62c1-cb6a-4898-b375-3feddc8b188f)

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
最新
### 2. 使用的ui库以及版本
- [] Antdv (版本？)
- [x ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.21.0已修复
