### ISSUE TITLE
字典 表格里自定义颜色

### ISSUE THREAD

**Issue by xiaozhangQAQ** [fast-crud/fast-crud#403]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
字典里data.color除了success,error...，这些以外能自定义颜色吗

- [x ] ElementPlus（版本？）

**Comment by greper** [comment]
antdv 是可以很多颜色的

**Comment by greper** [comment]
看tag组件是否支持
