### ISSUE TITLE
调用getAuthorization把alioss生成的key换成换成接口返回的path

### ISSUE THREAD

**Issue by feimao002** [fast-crud/fast-crud#405]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

大佬们好,咨询一个通过阿里云sts上传文件的问题,现在是在入门plugin配置文件里面配置了FsExtendsUploader的alioss,在getAuthorization中配置了后端返回的STS,但是后端同时返回了带有随机值的上传路径path,在这个alioss配置中路径是通过buildKey生成的,这样上传不成功
怎么样可以在调用getAuthorization把alioss生成的key换成这个接口返回的path呢

### 代码截图
`请贴出出错的相关代码截图`

![81715389969_ pic](https://github.com/fast-crud/fast-crud/assets/166683876/70f875d1-0ee0-4c0f-b1bb-13a757513d81)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
期望可以可以在调用getAuthorization把alioss生成的key换成这个接口返回的path
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？4.1)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.21.0 已支持getAuthorization接口中附加字段key即可替换前端生成的key
