### ISSUE TITLE
功能请求: 字典组件 fs-dict-tree 对插槽的支持

### ISSUE THREAD

**Issue by novaeye** [fast-crud/fast-crud#407]
## 一、问题描述
`当前版本的 fs-dict-tree 不支持插槽`(例如 [el-tree-select 的 prefix 插槽](https://github.com/element-plus/element-plus/blob/dev/docs/en-US/component/select.md#select-slots))

### 1. fast-crud版本：
`1.20.2`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（2.6）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.21.0已支持
http://fast-crud.docmirror.cn/element/#/crud/component/tree
