### ISSUE TITLE
子表格编辑BUG

### ISSUE THREAD

**Issue by haoqibbbb** [fast-crud/fast-crud#408]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
	actionbar: {
				buttons: {
					add: {
						show: false,
					},
					addRow: {
						show: false,
					},
				},
			},
上述addRow的show无效

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
最新版本
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`

- [ ] ElementPlus（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`

- [ ] fs-admin-element

**Comment by greper** [comment]
无效的效果截图

**Comment by greper** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/1687298/2f908089-2d6a-438d-bd4b-968dadb448ce)

示例中这些地方会触发开启，如果你要完全禁止addRow按钮，这些地方的代码你要删掉
