### ISSUE TITLE
【需求】- 获取字典label 

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#410]
## 一、问题描述
期望 `fast-crud` 可以根据获取 `dict-cascader` 的`value`、`label`
<img width="903" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/1ec5e599-b912-41bc-90e1-1b98aea828d0">

<img width="631" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/6bbbcc19-a76f-424e-87b7-58ed7a6e945c">

### 1. fast-crud版本：
`1.20.2`
### 2. 使用的ui库以及版本

- [x] Antdv (版本？)

### 3. 使用的admin框架
- [x] vben-admin

**Comment by greper** [comment]
1.21.0 dict-cascader组件已支持selected-change事件
