### ISSUE TITLE
在 fastCrud form 中使用 wang5 未能正确禁用以及没有正确触发表单验证

### ISSUE THREAD

**Issue by MikamiYuua** [fast-crud/fast-crud#412]
问题描述: 
1. 参照 https://github.com/fast-crud/fs-admin-naive-ui/blob/main/src/views/crud/component/editor/crud.jsx 使用了富文本编辑器
2. wang5 控件在 查看详情弹窗中并没有展现禁用的状态 
3. 在 表单的 rule 对 wang5 的值进行判空时表单触发了 validator 但是缺没有拦截

版本号: 
`"@fast-crud/fast-crud": "^1.20.2",
    "@fast-crud/fast-extends": "^1.20.2",
    "@fast-crud/ui-interface": "^1.20.2",
    "@fast-crud/ui-naive": "^1.20.2",`

代码片段 : 
`'attributes.desc': {
      title: '说明',
      key: 'attributes.desc',
      type: ['editor-wang5', 'colspan'],
      search: { show: false },
      form: {
        rule: [
          {
            required: true,
            trigger: 'blur',
            validator: async (_rule: any, value: string) => {
              if (value.trim() === '<p><br></p>' || value.trim() === '') {
                return new Error('内容不能为空');
              }
              return true;
            }
          }
        ],
        component: {
          id: 'admin-posts',
          disabled: compute(e => {
            if (e?.mode === 'edit' || e?.mode === 'add') {
              return false;
            }
            return true;
          }),
          uploader: {
            type: 'form',
            file_type: 'Files::ContentImg',
            async buildUrl(file: { attributes: ServerFile; file_url: string; id: string | number }) {
              return new Promise(resolve => {
                let url = '';
                if (file?.file_url) {
                  url = getImgUrl({ url: file.file_url });
                  if (isNumber(file.id)) resolve(url);
                }
                if (file?.attributes) {
                  url = getImgUrl({ url: file.attributes.file_url });
                  if (isNumber(file.attributes.id)) resolve(url);
                }
              });
            }
          }
        }
      }
    },`

**Comment by MikamiYuua** [comment]
![Uploading WechatIMG315.jpg…]()

**Comment by greper** [comment]
1.21.0示例已修复
http://fast-crud.docmirror.cn/antdv4/#/crud/component/editor
