### ISSUE TITLE
【组件】- 点击某个字段查询数据弹窗显示(数据是其他页面来的)

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#413]
## 一、问题描述
点击某个字段查询数据弹窗显示(数据是其他页面来的)

比如 【班级列表】 点击 某个班级 弹出 该班级学生   （数据来源是学生列表） 这样的情况应该不少，然后点击学生查看详情

组件可以兼容详情、列表后 fast-crud 可以简化更多的代码

 

### 效果截图

<img width="1727" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/cb9ab0a7-eb9d-46f6-9174-104270edfad2">

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
1.21.0 已支持
http://fast-crud.docmirror.cn/antdv4/#/crud/component/table-select
