### ISSUE TITLE
file-uploader配置sizeLimit后上传大于sizeLimit的文件，文件仍可以被正常输出

### ISSUE THREAD

**Issue by Bakasamaw** [fast-crud/fast-crud#414]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
file-uploader配置了sizeLimit后，我上传了一个大于sizeLimit的文件，按照正常的需求是这个文件不应该被输出，但是在antdv中仍可以显示。

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`
http://fast-crud.docmirror.cn/antdv/#/crud/component/uploader/form
点击添加，点击限制大小处的文件上传按钮，然后上传一个大于1kb的文件。

### 代码截图
`请贴出出错的相关代码截图`
![image](https://github.com/fast-crud/fast-crud/assets/69292315/44db639e-3e7e-4391-bba9-f2c2b9e1cf47)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![image](https://github.com/fast-crud/fast-crud/assets/69292315/245bfef4-6ba5-49f4-905a-7e73fadd0ab6)

#### 2. 实际效果
![image](https://github.com/fast-crud/fast-crud/assets/69292315/58715be1-2bbe-4bf4-9b97-221570e7f906)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
antdv的问题 无法解决，建议到antdv开源库去提问
