### ISSUE TITLE
设置搜索按钮=false，不生效

### ISSUE THREAD

**Issue by zuihou** [fast-crud/fast-crud#415]
```
toolbar: { search: false, compact: false },
```
根据源码中的注释，我想将搜索框默认隐藏，
但配置toolbar.search=false 时，页面首次加载时，还是显示了搜索框。

（备注： 配置toolbar.compact=false 时，页面首次加载时，已经不是紧凑模式了。）

<img width="645" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/2dc79222-ee82-42c2-a26c-0d8f8e72246f">

<img width="516" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/33e57863-0863-4854-957b-ec52da18b9ef">

**Comment by greper** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/1687298/9b775e01-0748-4bb6-91c2-ccd1adeadcdb)

**Comment by zuihou** [comment]
不是隐藏搜索框， 是页面进入时，默认这种效果：


<img width="1340" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/cbe6329c-842f-4456-9eb2-48f6ee1634c1">
