### ISSUE TITLE
viewFormUseCellComponent 在 type 为数组时，不生效

### ISSUE THREAD

**Issue by zuihou** [fast-crud/fast-crud#416]
version: 1.21.0
配置： 
```
settings: { viewFormUseCellComponent: true }, 
columns: {
     execTime: {
          title: 'xxxx',
// viewFormUseCellComponent设置为true时， 若type 设置为['text'] viewFormUseCellComponent属性不生效。
          type: ['text'],
        },
}
```

- viewFormUseCellComponent设置为true时， 若type 设置为['text'] viewFormUseCellComponent属性不生效。
-  viewFormUseCellComponent设置为true时， 若type 设置为'text' viewFormUseCellComponent属性生效。

**Comment by zuihou** [comment]
<img width="985" alt="image" src="https://github.com/fast-crud/fast-crud/assets/8500410/4607b141-827f-40ff-8eeb-bdf2ed4b04c5">

另外，建议：  若type=’text' ，且用户自定义了render，显示用户自定义的render

**Comment by greper** [comment]
已修复
