### ISSUE TITLE
[提议] `Row`字段与列关系能解耦

### ISSUE THREAD

**Issue by NHZEX** [fast-crud/fast-crud#417]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述

1. CURD声明的字段能完全解耦，定义字段工作的场景（`column`,`form`,`search`）

> 比如`Row`的某个字段是不参与表格交互的，只做编辑、查看或者搜索使用，但目前只能通过`show`来隐藏（没有与表格这个元素真正的解绑），如果不做处理是能工具栏中是能直接重新显示的。   
> 解耦也有助于下面提出的虚拟字段概念。   

2. 需要有一个虚拟字段概念，来表达并不实际存在于 Row 数据中。

> 这个定义最简单目的是渲染一个列，不与`Row`某个字段是单一关系的。
> 某些字段只服务于场景（`form`,`search`），或者只做表单提交使用，不在`Row`中关联具体值。

---

我刚尝试这个组件，对其用法还没有深入理解，以上问题基于文档+demo的浅度使用提出的。
比如`deme`中的动态计算效果与提出虚拟字段的结果差不多，但觉得有个更明确的定义会好些，可以衍生出更完善的定义选项。  

我就是在尝试使用这个组件迁移现有接口时觉目前字段定义比较耦合，稍微复杂点的 CRUD 功能中很多字段在不同场景（`column`,`form`,`search`）下的读写都是是处于解耦关系，如果用围绕`columns`集中定义的做法会很比较难受（或许这个用法是错的）。

PS： 我看文档好像是能CURD的各个部分应该是能单独定义的，但还没尝试，当前`demo`或文档中主要提醒是以表格列为中心去衍生表单的定义，耦合比较重，可能需要针对这种解耦场景有明显的提示。

我想法中的设计：围绕字段（`Row`中的字段只是其子集）定义不同场景下如何工作，类似定义一个配置表，然后再解析拆分到不同的组件中去初始化。

以上问题仅是对于组件的粗浅理解，如果理解有误或者当前已经能实现谢谢指出。  

### 1. fast-crud版本：
`1.21.0`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv
- [ ] ElementPlus
- [x] NaiveUI（`2.38.2`）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`soybean-admin`

**Comment by greper** [comment]
你可以直接使用crudBinding来定义，在crudBinding里面，column、form、search是独立的

**Comment by greper** [comment]
不想用的字段 你用show关闭即可

**Comment by greper** [comment]
1、 比如Row的某个字段是不参与表格交互的，只做编辑、查看或者搜索使用，但目前只能通过show来隐藏（没有与表格这个元素真正的解绑），如果不做处理是能工具栏中是能直接重新显示的。 
http://fast-crud.docmirror.cn/api/crud-options/columns.html#key-column-columnsetshow  这个配置可以隐藏工具栏中的显示

2、 虚拟字段这个概念挺好，不过就是动态计算就可以实现，并且就算你把字段定义为虚拟字段了，还是用通过动态字段的配置来告诉单元格如何显示

**Comment by greper** [comment]
我想法中的设计：围绕字段（Row中的字段只是其子集）定义不同场景下如何工作，类似定义一个配置表，然后再解析拆分到不同的组件中去初始化。

你的这个想法 不就是我现在的做法？？？

columns 是字段不同场景下的配置，然后通过useFs 转换成crudBinding, 这个crudBinding就是拆解到不同的组件中了

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/guide/advance/column-type.html#%E5%AD%97%E6%AE%B5merge%E6%8F%92%E4%BB%B6

可以试试字段merge插件

**Comment by greper** [comment]
Row中的字段只是其子集）
columns.key.column（就是你说的row）  、 columns.key.search、columns.key.form 本来就是并列的
