### ISSUE TITLE
修改某条数据后，只希望这一行数据更新

### ISSUE THREAD

**Issue by renzetong** [fast-crud/fast-crud#420]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
   使用 async updateCell 的时候知道更新的是第几行，expose?.updateTableRow也就无法知道是第几行数据需要更新，
   
![image](https://github.com/fast-crud/fast-crud/assets/83214982/351f4d71-b98e-4533-a84e-7184f1a98ed1)
我不知道还有什么办法可以获取修改的是第几行，举例：在修改的时候一页如果有20条数据，他最大返回的行数页应该是20，目前是从第一页直接跳到第六页或者其他页数，修改地2行，editableId返回的就是第一页条数20+2，我理解的是他应该返回的是2不应该是22
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
修改后只对单行数据进行更新
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by renzetong** [comment]
![Uploading 1718784341744.jpg…]()

**Comment by greper** [comment]
![image](https://github.com/fast-crud/fast-crud/assets/1687298/45b42dfd-5179-4caa-96a4-e0b1843ccc92)
