### ISSUE TITLE
table-select 查看模式下点击确认会更改modelValue

### ISSUE THREAD

**Issue by YusraL2** [fast-crud/fast-crud#421]
## 一、问题描述

- table-select 在 viewMode 查看模式做查询等会改变 table 数据的操作并点击 wrapper 的确认按钮后，该 row 中此字段的 modelValue 也会被一起改变（真实环境下表现为从字段的 modelValue 列表中去除查看模式下查询出的数据），导致之后该 row 表单数据错误
- table-select 在编辑模式下 valuesFormat 的 tag 点击关闭后，表格中数据的复选框未同步取消勾选

### 复现步骤
官方示例中可复现

![image](https://github.com/fast-crud/fast-crud/assets/156041340/f4b0ab39-3d56-4dce-9b66-d3fc17404ad7)
![image](https://github.com/fast-crud/fast-crud/assets/156041340/c0c08ff5-37dc-4f1b-885e-f0464923e90f)

点击查看之后，将班级id修改为其他值，并点击确认，row 中的值也被改变

![image](https://github.com/fast-crud/fast-crud/assets/156041340/0a3505c6-b38d-4b16-9ce3-b6ba61abc2d6)

表单上方 valuesFormat 的 tag 点击关闭后，表格中数据的复选框未同步取消勾选

### 1. fast-crud版本：
`1.21.0`
### 2. 使用的ui库以及版本
- [x] ElementPlus（版本2.6.0）

### 3. 使用的admin框架
- [x] fs-admin-element

**Comment by greper** [comment]
1.21.1已修复
