### ISSUE TITLE
需求 - 在使用dict-tree的时候，最好在name前面能插入图标或者自定义name显示方式

### ISSUE THREAD

**Issue by gutYes** [fast-crud/fast-crud#423]
## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
## 在使用dict-tree 的时候，返回的name太过于单一，例如使用国家，在返回name同时的情况下，返回图标+name 同时显示。
![image](https://github.com/fast-crud/fast-crud/assets/155432072/34e59d9a-6a7a-421c-a732-d582d96e3848)

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![image](https://github.com/fast-crud/fast-crud/assets/155432072/ea7cf864-5e05-40ae-ae98-97f7cb8ef2a6)
图标与name是两个字段，最终展示，最好能给出自定义返回效果
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
截图的里面的示例本来就是有自定义label显示的

我再改了一下示例，把图标也加上了
![image](https://github.com/fast-crud/fast-crud/assets/1687298/df72ef8f-12f2-4599-b365-947206bf60e6)
