### ISSUE TITLE
【BUG】子表格编辑日期bug

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#425]
## 一、问题描述
[http://fast-crud.docmirror.cn/antdv4/#/crud/editable/vmodel ](http://fast-crud.docmirror.cn/antdv4/#/crud/editable/vmodel )
参考案例 

- 写了如下字段（神奇的问题是 查询没问题,编辑的时候日期渲染异常）

``` 
        expiryDate: {
          title: "失效日期",
          type: "date",
          search: { show: false },
          column: { show: true, width: 160 },
          valueResolve({ value, row, key }) {
            if (value != null) {
              row[key] = dayjs(value).unix();
            }
          },
          valueBuilder({ value, row, key }) {
            if (value != null) {
              row[key] = dayjs(value);
            }
          },
          form: {
            component: { format: "YYYY-MM-DD" },
            rules: [{ required: true, message: "请输入失效日期" }],
          },
        },
```

<img width="1695" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/93601685-0b07-480d-8bff-785ca0cec0db">

### 代码截图
<img width="891" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/3d5f4662-8b57-463f-a1f6-6475ff3fede4">

### 报错截图

<img width="691" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/88d69ca2-b909-490e-8812-c5c8bc2fe9fe">

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
期望编辑 也能像详情一样正常
<img width="1695" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/1e7da915-a73c-4144-afa6-707e733b3672">

#### 2. 实际效果
<img width="1723" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/362802aa-1ea9-44ad-a920-4bba39fe4981">

### 1. fast-crud版本：
1.12.0
### 2. 使用的ui库以及版本

- [x] Antdv (版本？)

### 3. 使用的admin框架
- [x] vben-admin

**Comment by levin950825** [comment]
通过如下写法就可以成功，但是感觉应该可以优化一下 
``` 
        expiryDate: {
          title: "失效日期",
          type: "date",
          column: { show: true, width: 120 },
          valueResolve({ value, row, key }) {
            if (value != null) {
              row[key] = dayjs(value).unix();
            }
          },
          valueBuilder({ value, row, key }) {
            if (value != null) {
              row[key] = dayjs(value);
            }
          },
          form: {
            component: { format: "YYYY-MM-DD", valueFormat: "YYYY-MM-DD" },
            rules: [{ required: true, message: "请输入失效日期" }],
          },
        },
```

**Comment by greper** [comment]
这需要你自己进行处理的  
无法保证用户输入的格式 都是  valueFormat: "YYYY-MM-DD"， 所以只能用户自己配置
