### ISSUE TITLE
【需求】- 子表格自由编辑插槽无效

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#431]
## 一、问题描述
<img width="1438" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/a82f5de0-0091-4670-bd32-17bd37a96fd4">

<img width="1418" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/32344a18-cedf-4e5b-943c-21550693c8ac">

### 复现步骤
子表格自由编辑插槽无效

### 代码截图
<img width="442" alt="image" src="https://github.com/fast-crud/fast-crud/assets/13896536/7750b79a-9108-4662-b12e-55f5f5c30576">

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.22.1已修复
