### ISSUE TITLE
file-uploader组件预览时存在bug

### ISSUE THREAD

**Issue by haoqibbbb** [fast-crud/fast-crud#432]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
组件上传成功后，行模式下点击预览正常，form模式下点击地址有误

### 复现步骤
行模式下预览正常
![image](https://github.com/user-attachments/assets/da9f78c6-0163-43cb-980c-f6a6177a2db1)

表单模式下点击
![image](https://github.com/user-attachments/assets/5e70ac54-d23f-425f-90c0-2cbda7a867ca)
![image](https://github.com/user-attachments/assets/56683028-034a-496c-a9a7-355831ccdba2)
似乎没有正确获取baseURL

### 代码截图
![image](https://github.com/user-attachments/assets/a9a64f4c-c766-4390-9ca7-b28a025d8823)

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
最新版本
### 2. 使用的ui库以及版本
-ElementPlus

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
![image](https://github.com/user-attachments/assets/76f874e2-c9c0-4463-bf82-061fba1247be)
