### ISSUE TITLE
【需求】- 直接使用crudBinding的表单配置不支持插槽

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#435]
## 一、问题描述

直接使用crudBinding的表单配置不支持插槽。

### 代码截图
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/45dbf576-6fc4-46c7-8655-cc08e0bcd912">
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/00a6e5f8-196c-485f-8de3-83a1ad014ec2">

<img width="982" alt="image" src="https://github.com/user-attachments/assets/f8d517a3-2cea-4794-a7d8-6ea740ca5a3f">

### 1. fast-crud版本：
1.21.2
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
1.22.1已修复
