### ISSUE TITLE
【需求】- 表单希望支持左右插槽 #435

### ISSUE THREAD

**Issue by wanpong007** [fast-crud/fast-crud#436]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`单希望支持左右插槽，方便在表单中左侧或者右侧显示对应的内容，比如
![image](https://github.com/user-attachments/assets/4adc1016-d48f-4ef7-968d-904f757d1304)

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
![image](https://github.com/user-attachments/assets/802b88e5-eeb1-4753-9f4c-fbf7f1d4e694)
### 1. fast-crud版本：
1.21.2
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.22.1已支持
