### ISSUE TITLE
【BUG】- from 的 wrapper.onClosed 方法调用报错

### ISSUE THREAD

**Issue by duanshuo198802** [fast-crud/fast-crud#437]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
调用 from 的 wrapper.onClosed 方法调用报错，错误信息为
```
Uncaught TypeError: Cannot read properties of null (reading 'mode')
    at D (fs-form-wrapper.tsx:104:33)
    at d2.value (fs-form-wrapper.tsx:142:28)
    at M (fs-form-wrapper.tsx:241:22)

```

### 复现步骤
```
form: {
        wrapper: {
          onOpened: () =>{
            console.log('1111111111111111')
          },
          beforeClose: () =>{
            console.log('2222222222222222')
          },
          onClosed: () =>{
            console.log('3333333333333333')
          },
        }
      },

onOpened和beforeClose执行没有问题，onClosed执行会报错
```
### 报错截图
```
Uncaught TypeError: Cannot read properties of null (reading 'mode')
    at D (fs-form-wrapper.tsx:104:33)
    at d2.value (fs-form-wrapper.tsx:142:28)
    at M (fs-form-wrapper.tsx:241:22)

```

### 效果截图
无

### 疑似报错原因
/fs-form-wrapper.tsx 文件的239行 formOptions.value = null;将fromOptions设置为null后执行  buildEvent方法时报错

```
    const onClosed = () => {
      formOptions.value = null;
      if (emitOnClosed.value) {
        emitOnClosed.value();
      }
      ctx.emit("closed");
    };
```

### 1. fast-crud版本：
1.21.2
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`)
- [x] ElementPlus（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] 其他：pureadmin

**Comment by levin950825** [comment]
["http://fast-crud.docmirror.cn/antdv4/#/crud/form/independent"](http://fast-crud.docmirror.cn/antdv4/#/crud/form/independent)  
<img width="1518" alt="image" src="https://github.com/user-attachments/assets/44b42ad8-9498-489b-ab2e-3d36b89fe736">
在线案例同样存在问题

**Comment by greper** [comment]
1.22.1已修复
