### ISSUE TITLE
点击左侧tree控件，实现右侧表格列表刷新

### ISSUE THREAD

**Issue by nsh635211** [fast-crud/fast-crud#44]
您好，请问有相关的API点击左侧tree控件，实现右侧表格列表刷新（pageRequest），如下图
![002](https://user-images.githubusercontent.com/78367271/150621086-c1922808-81da-4360-ac30-bc7213303280.png)

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/antdv/#/crud/advanced/nest
你可以参考这个示例，将左边的表格换成树形组件即可

**Comment by leishaoxiong** [comment]
左侧 tree控件点击的时候，query打印出来是没有参数值的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fast-crud/fast-crud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月22日(星期六) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fast-crud/fast-crud] 点击左侧tree控件，实现右侧表格列表刷新 (Issue #44)





 
http://fast-crud.docmirror.cn/antdv/#/crud/advanced/nest
 你可以参考这个示例，将左边的表格换成树形组件即可
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leishaoxiong** [comment]
你好，当我通过setSearchFormData，设置form值的之后，执行doRefresh()，请求的参数里并没有form的表单值
![Uploading 005.png…]()

**Comment by leishaoxiong** [comment]
你好，当我通过setSearchFormData，设置form值的之后，执行doRefresh()，请求的参数里并没有form的表单值
![005](https://user-images.githubusercontent.com/78367271/150752309-103b2c39-9c6d-4f58-82cf-c6a658789d58.png)

**Comment by greper** [comment]
rightContent.value 是什么？
getSearchFormData 是expose里的方法

**Comment by leishaoxiong** [comment]
rightContent.value是ref拿到的左侧tree数据，getSearchFormData是我在rightContent里面通过expose拿到并返回的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月24日(星期一) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fast-crud/fast-crud] 点击左侧tree控件，实现右侧表格列表刷新 (Issue #44)





 
rightContent.value 是什么？
 getSearchFormData 是expose里的方法
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
