### ISSUE TITLE
【BUG】-table-select 使用 自定义插槽方式打开后，没有刷新数据问题

### ISSUE THREAD

**Issue by wanpong007** [fast-crud/fast-crud#440]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
table-select 使用 自定义插槽方式打开后，没有刷新数据问题
![image](https://github.com/user-attachments/assets/290027ab-d86f-40b2-b8f3-ae7d856785df)

### 复现步骤
在http://fast-crud.docmirror.cn/antdv4/#/crud/component/table-select示例网站中，打开后直接点击自定义插槽
的选择按钮

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
![image](https://github.com/user-attachments/assets/955a4a8c-0a2a-4048-8385-b9e7cefc8639)

### 效果截图
![image](https://github.com/user-attachments/assets/0a0e92aa-7b57-4f9a-b9fc-334024ed2157)
#### 2. 实际效果
![image](https://github.com/user-attachments/assets/667cbf8b-9d70-4045-a924-cf32b636b076)

### 1. fast-crud版本：
`请您填写fast-crud的版本`[1.21.2]
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.22.1已修复
