### ISSUE TITLE
fs-table-select中，我点击取消，后面再点击进去的时候，多选框还会默认保留上一次，这个怎么设置清除上一次的记录呢？

### ISSUE THREAD

**Issue by nidebin** [fast-crud/fast-crud#441]
## 一、问题描述
fs-table-select中， 我第一次进去点击多选框，进行选择后，点击了取消或确认，下次再进入时，多选框会保留上一次选择的内容，这个怎么清除掉呢？
我设置scope.select=null， 也没有效果

### 复现步骤
1、点击fs-table-select按钮，
2、在多选框中进行选择
3、点击取消或者确认
4、再次进入后，多选框保留了上次选择的内容，请问这个怎么清除呢？

### 代码截图
![image](https://github.com/user-attachments/assets/f1f07524-a9f9-4222-ad33-ce40c29e10a0)
![image](https://github.com/user-attachments/assets/f0271e25-e892-4e5e-be60-0707814e3de6)

#### 1. 期望效果
select多选框，进入后，能进行配置，可以清除上一次选择的内容，希望可以设置为可以配置的
#### 2. 实际效果
不能清除上一次选择的，会保留上一次已经多选上的结果

### 1. fast-crud版本：
1.21.2
### 3. 使用的admin框架
- [x] fs-admin-antdv
- [ ] fs-admin-element

**Comment by breadlees** [comment]
这个问题和在crudOptions中设置selectedRowKeys
```
settings: {
				plugins: {
					//这里使用行选择插件，生成行选择crudOptions配置，最终会与crudOptions合并
					rowSelection: {
						enabled: true,
						order: -2,
						before: true,
						// handle: (pluginProps,useCrudProps)=>CrudOptions,
						props: {
							multiple: true,
							crossPage: true,
							selectedRowKeys,
							onSelectedChanged(selected) {
								// console.log("已选择变化：", selected);
								// showButtonCopy.value = selected.length === 1;
							}
						}
					}
				}
			},
```

然后用
```
selectedRowKeys.value = []; // 清空 selectedRowKeys
```
去清空但无效，应该是同一个问题，在群里和作者反馈了，不知道作者什么时候有时间来修这个

**Comment by greper** [comment]
已修复
