### ISSUE TITLE
n-popover 控件与 fs-cropper-uploader 存在逻辑冲突

### ISSUE THREAD

**Issue by MikamiYuua** [fast-crud/fast-crud#443]
我在 使用navieUI 版本的时候发现 n-popover 中嵌套使用 fs-cropper-uploader , 
当 fs-cropper-uploader 打开之后会造成  n-popover 失焦而关闭 , 

在代码上应该是 packages/fast-extends/src/uploader/components/fs-cropper.vue 文件 中的 append-to-body 属性造成的。 

建议开放此属性 , 可以指定 fs-cropper-uploader 追加到  n-popover 控件元素上从而避免失焦关闭 .

tks

**Comment by MikamiYuua** [comment]
如果用户唤起了系统的文件选择器之后 , n-popover 仍然会失焦 ; 所以我刚刚提出的问题好似是一个伪需求 🥱 ;

**Comment by greper** [comment]
你让他popover不自动消失就行了
