### ISSUE TITLE
actionbar和search能放一行吗

### ISSUE THREAD

**Issue by T-HuLu** [fast-crud/fast-crud#444]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`能将actionbar中的新增按钮，和search中的按钮放一行吗。`

### 效果截图
![image](https://github.com/user-attachments/assets/553c0e7a-ab26-4fe8-8873-5a103e5d3a7d)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [x] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
http://fast-crud.docmirror.cn/guide/advance/layout.html#_1-1-crud%E4%B8%BB%E7%95%8C%E9%9D%A2%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80

使用自定义布局
