### ISSUE TITLE
radio和checkbox的警告问题

### ISSUE THREAD

**Issue by zsbugs** [fast-crud/fast-crud#449]
## 一、问题描述
由于element升级，新版本中使用fs-dict-radio和fs-dict-checkbox会出现警告

### 报错截图
![image](https://github.com/user-attachments/assets/fe7e45bb-6ecf-40af-8dfa-b6dbc2a54a2d)

### 1. fast-crud版本：
1.13.2
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`

- [ ] ElementPlus（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`

- [ ] fs-admin-element

**Comment by greper** [comment]
已修复
