### ISSUE TITLE
多级表头子列调整顺序未记录问题

### ISSUE THREAD

**Issue by sdevnetcn** [fast-crud/fast-crud#454]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

一、问题描述
多级表头调整子列顺序时界面未更新
二、问题描述
建议把调整列宽后的列宽度也记录起来
三、当前使用的库版本
1. fast-crud版本：
el-admin 的最新的多级表头demo

**Comment by greper** [comment]
1.22.1已修复
