### ISSUE TITLE
antdv 版本 pagination 不显示

### ISSUE THREAD

**Issue by zmice** [fast-crud/fast-crud#458]
## 一、问题描述
antdv 版本 pagination 不显示，官方示例也没有

### 复现步骤
官方示例也没有

### 效果截图
![QQ20241112-125059](https://github.com/user-attachments/assets/e06986a7-7484-4538-93fe-3fbaf26fef3b)
#### 1. 期望效果
分页正常
### 2. 使用的ui库以及版本
- [x] Antdv (版本 4.2.5)

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
升级到最新版
