### ISSUE TITLE
Module not found: Error: Can't resolve './iterator.js'

### ISSUE THREAD

**Issue by HandsomeWolf** [fast-crud/fast-crud#47]
in ./node_modules/_@fast-crud_fast-crud@1.0.0-alpha.6@@fast-crud/fast-crud/dist/fast-crud.es.js

**Comment by greper** [comment]
信息太少

**Comment by FzerozZ** [comment]
在webpack 下   编译vue3.0项目  ./node_modules/_@fast-crud_fast-crud@1.0.0-alpha.7@@fast-crud/fast-crud/dist/fast-crud.es.js
该文件  2366行  引入 './iterator.js' 报错   好像是yallist的模块的

**Comment by greper** [comment]
请提供一个最小示例代码仓库地址，我这边运行试试

**Comment by zrad** [comment]
也出现了这个问题。
![image](https://user-images.githubusercontent.com/15223877/167537827-3dbde2b3-9887-46a1-bc87-2b79d6e94d6d.png)

**Comment by zrad** [comment]
https://gitee.com/lolicode/scui 这个作者的框架 直接加载fast-crud后 就会报这个错。升级下还会出现https://github.com/fast-crud/fast-crud/issues/65 这个问题。都是同一个框架。 isCE的问题不常出。

**Comment by greper** [comment]
我有空去集成这个框架试试

**Comment by greper** [comment]
报错是这一行出来的，实际上不影响运行，可以不用管它
![image](https://user-images.githubusercontent.com/1687298/170862357-af73ba25-c10c-449e-976c-eb7398257ef3.png)

**Comment by greper** [comment]
fs-in-scui
http://fast-crud.docmirror.cn/scui/#/fastcrud
