### ISSUE TITLE
TypeError: date4.locale is not a function

### ISSUE THREAD

**Issue by jesse996** [fast-crud/fast-crud#48]
用fast curd + antd vue ,datetime类型如2021-08-30T16:00:00，点击编辑的时候会报这个错

**Comment by greper** [comment]
antdv的datetime组件的value需要转化为dayjs 或者moment传入

**Comment by greper** [comment]
![image](https://user-images.githubusercontent.com/1687298/157837134-d843397d-e94f-45ca-9fc8-6ff0192285fc.png)
