### ISSUE TITLE
如果想对表格列表数据根据dict数据做一些操作比较难办,比如后台没有返回label只返回id

### ISSUE THREAD

**Issue by github-du** [fast-crud/fast-crud#49]
valueBuilder 执行时有可能assetPackageList 还没获取到数据

`  const assetPackageList = ref([]);
  const assetPackageDict  = dict({
    async getData() {
      const res = await api.assetPackageList();
      assetPackageList.value = res;
      return res;
    },
    label: "code",
    value: "id"
  })

------------------crudOptions.columns
assetPackageName: {
          title: "项目名称",
          type: "text",
          form: {
            component: {
              disabled: true
            }
          },
          valueBuilder(context) {
            const id = context.row.assetPackageId;
            const target = assetPackageDict.getNodeByValue(id)
            console.log('项目名称, 拦截')
            if(!target){
              setTimeout(()=>{
                const target = assetPackageDict.getNodeByValue(id)
                console.log(target, '项目名称, 拦截')
                context.row.assetPackageName = target ? target.name : "";
              },4)
            }else {
              context.row.assetPackageName = target.name;
            }
          }
        }`

**Comment by greper** [comment]
可以在pageRequest里面  await assetPackageDict.loadDict() 
或者在mountd(async ()=>{
await assetPackageDict.loadDict() 
expose.refresh()
})
