### ISSUE TITLE
utils.log.ts使用vite build打包时会自动移除console.log，导致代码运行错误

### ISSUE THREAD

**Issue by cmlibo** [fast-crud/fast-crud#54]
utils.log.ts中有以下代码

`const info = (...args) => {
  console.log("[info]", ...args);
};
const debug = (...args) => {
  const callerInfo = getCallerInfo();
  if (DEBUG_WITH_CALLER) {
    console.log("[debug]", ...args, "\n", callerInfo);
  } else {
    console.log("[debug]", ...args);
  }
};`

新版的vite 默认使用 minify: 'terser'，会去除 console.log console.debug
打包出来就会变成
warn=(...H)=>{console.warn("[warn]",...H)},info=(...H)=>{...H},debug=(...H)=>{const C=getCallerInfo();...H}
代码会直接就无法运行
vite使用的esbuild，有规则可以跳过这个，详见以下网址
https://esbuild.docschina.org/api/#pure

**Comment by greper** [comment]
我这边没有复现出来

**Comment by greper** [comment]
1.2.0应该可以了，再测试测试
