### ISSUE TITLE
TypeError: normalizeKey is not a function

### ISSUE THREAD

**Issue by zrad** [fast-crud/fast-crud#55]
![image](https://user-images.githubusercontent.com/15223877/165878858-d053f1b4-73a9-4335-8916-939984d3eb11.png)

![image](https://user-images.githubusercontent.com/15223877/165879205-f2f1b563-a03c-4b0b-9c08-ffb2e80658cf.png)

Vue3 没有TS。请教为什么导入不到项目内

**Comment by zrad** [comment]
@greper 大佬 能给解释下为什么吗？npm yarn pnpm都试过了。按照文档就提示这个。缺什么依赖吗？

**Comment by greper** [comment]
报错截图有点短，add-location这个不太确定跟什么有关。
或者你升级element-plus试试

**Comment by zrad** [comment]
![image](https://user-images.githubusercontent.com/15223877/167525543-8507dc08-17a0-442f-b465-ca3c0596fc47.png)
![image](https://user-images.githubusercontent.com/15223877/167525597-b30151fe-39a0-4fda-a83f-668d3ef0ea55.png)

**Comment by greper** [comment]
你看看addlocation是被什么组件引用的？

**Comment by zrad** [comment]
vscode搜addLocation 没有组件引用。是这么查吗？

**Comment by zrad** [comment]
噢。elementplus刚升级的2.2.0 也是如此。

**Comment by greper** [comment]
无法复现
