### ISSUE TITLE
项目没有导出ts定义文件吗

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#57]
如题

**Comment by greper** [comment]
应该是有导出的，你遇到什么问题？截图看看

**Comment by jingjingzhao** [comment]
> 应该是有导出的，你遇到什么问题？截图看看

嗯，确实有导出。现在主要想看配置 crudOptions 的ts文件，我看源码里基本只定义了最外层的key，每个key的类型并没有明确定义。这个可以补充吗？

现在写代码，需要经常查看源码
![image](https://user-images.githubusercontent.com/5880014/167624952-c339c54a-07c7-4924-b811-1d0c49a4bdca.png)

**Comment by greper** [comment]
有空我再完善完善吧

**Comment by greper** [comment]
已经加了一个初步版本，后续再逐步完善
http://fast-crud.docmirror.cn/d.ts/modules.html
