### ISSUE TITLE
弹窗最大化和关闭按钮错位

### ISSUE THREAD

**Issue by zrad** [fast-crud/fast-crud#58]
element-plus 2.2.0
添加弹窗 最大化和关闭错位
![image](https://user-images.githubusercontent.com/15223877/167749117-7f80effb-4507-4ed2-b0b6-b89d261a3c4e.png)

**Comment by zrad** [comment]
那啥时候更新npm包呢？还是我不太懂怎么能用大佬你修复后的npm @greper

**Comment by greper** [comment]
还没发布，等我发布了 你修改package里面的fast-crud的版本号，然后npm install一下就行
