### ISSUE TITLE
fast 0.11.0 使用建议

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#6]
### 头像和操作栏错位
![57831625320913_ pic_hd](https://user-images.githubusercontent.com/13896536/124372165-5f40a800-dcbb-11eb-80bf-397edd7dc379.jpg)

### 设置成更多按钮的时候 即使设置了 text 依旧有...
![58331625369176_ pic](https://user-images.githubusercontent.com/13896536/124372178-7384a500-dcbb-11eb-9c55-9ae448d8f92d.jpg)

**Comment by greper** [comment]
1、iconify已支持
2、这个只有在第一次加载的时候会出现，可以在 `App.vue`中插入一个`<fs-images-format/>`事先将这个异步组件先加载出来，就没有问题了。
3、这个是图标，需要配置 `more.icon=null`才能将其消除
