### ISSUE TITLE
fs-in-vben-starter build 版本无法正常工作， Unexpected token '...'

### ISSUE THREAD

**Issue by vellengs** [fast-crud/fast-crud#60]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/5743338/168415154-a86a9d12-62ea-4537-807e-6096db53df63.png">

**Comment by vellengs** [comment]
直接在 [vben-admin](https://github.com/anncwb/vue-vben-admin) 项目中引入 fs crud 也一样的问题。

**Comment by vellengs** [comment]
已找到问题：
<img width="566" alt="image" src="https://user-images.githubusercontent.com/5743338/168422561-65873fdd-a4fe-43ef-a45e-826f5e947c69.png">

**Comment by greper** [comment]
所以是什么问题？

**Comment by vellengs** [comment]
Build 之后的产品版本，无法运行。

**Comment by jesse996** [comment]
我也是这个问题，咋解决的啊？
