### ISSUE TITLE
搜索栏的按钮布局扩展性不友好

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#63]
搜索栏的按钮布局扩展性不好。
现在没办法将 三个按钮放在一排，也不能将三个按钮排在 推送时间输入框的后面
![image](https://user-images.githubusercontent.com/5880014/169734780-83df00c8-4045-41b9-9732-dcc975c4132d.png)

**Comment by greper** [comment]
1.2.0 你说的这两种都可以实现
http://fast-crud.docmirror.cn/antdv/#/crud/feature/search-multi
点击切换模式按钮查看效果
