### ISSUE TITLE
antd-design-vue 使用crud底部显示两个分页

### ISSUE THREAD

**Issue by EightDoor** [fast-crud/fast-crud#64]
## 一、问题描述
底部显示两个分页，我看配置表格也没有提供配置禁用表格分页
![image](https://user-images.githubusercontent.com/35022264/170172655-1df01093-45fe-4906-8c9a-0e59163f76f0.png)
#### 1. 期望效果
可以禁用默认表格分页

### 1. fast-crud版本：
    "@fast-crud/fast-crud": "^1.2.0",
    "@fast-crud/ui-antdv": "^1.2.0",
### 2. 使用的ui库以及版本
    "ant-design-vue": "^3.2.3"

**Comment by greper** [comment]
安装fast-crud传入的公共配置里面有禁用
![image](https://user-images.githubusercontent.com/1687298/170173094-6b0dc537-339e-426b-9d4e-bc368459650a.png)
