### ISSUE TITLE
升级到1.2.0后，TypeError: Cannot read property 'isCE' of null

### ISSUE THREAD

**Issue by zrad** [fast-crud/fast-crud#65]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
升级到1.2.0后，TypeError: Cannot read property 'isCE' of null

### 复现步骤
npm 升级后再打开就这样了。vue3+js

### 报错截图
![image](https://user-images.githubusercontent.com/15223877/170186574-b3765de5-4d95-46a0-a6ea-595e8c1e7035.png)

### 1. fast-crud版本：
`1.2.0`
### 2. 使用的ui库以及版本

- [x] ElementPlus（版本？2.2.0）

**Comment by zrad** [comment]
换回1.1.2 没问题。@greper

**Comment by greper** [comment]
上面报错截图，红色的展开看一下

**Comment by zrad** [comment]
![image](https://user-images.githubusercontent.com/15223877/170193419-37bc12f7-4737-429a-9e1c-55837dea57b0.png)
![image](https://user-images.githubusercontent.com/15223877/170193465-dc30fdd4-b4dd-4a4e-bd9c-59bbe1817f54.png)
![image](https://user-images.githubusercontent.com/15223877/170193553-a95ed487-5600-48dd-b594-0bc6631e8371.png)

**Comment by greper** [comment]
我这边没有复现，能否提供一个最小复现示例

**Comment by greper** [comment]
我集成了scui，暂时无法复现，先关闭此问题，如果你那边仍然出现，你可以提供一个复现示例，再次打开此问题
http://fast-crud.docmirror.cn/scui/
