### ISSUE TITLE
希望新增一个空白表单组件，只是用来占位。

### ISSUE THREAD

**Issue by crstudio** [fast-crud/fast-crud#67]
因为有些地方需要一整行来放置一个类似文本框这样的组件，但是输入框却不需要很宽，这样看着不太美观，所以需要一个占位的空白表单组件，或者给form增加配置，占用一行，但是宽度只显示12.

**Comment by greper** [comment]
1.2.3已支持
http://fast-crud.docmirror.cn/api/crud-options/columns.html#key-form-blank

**Comment by crstudio** [comment]
thanks!
