### ISSUE TITLE
操作列如何居中显示？

### ISSUE THREAD

**Issue by zrad** [fast-crud/fast-crud#69]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

### 代码截图
![image](https://user-images.githubusercontent.com/15223877/176078401-e3f27d0e-a2c7-4080-a06b-d0254aa91924.png)
![image](https://user-images.githubusercontent.com/15223877/176078526-dd0ddddc-13f8-4753-bfba-0e3a88a90af3.png)

### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [x] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] 其他：SCUI

**Comment by greper** [comment]
配置 rowHandle:{ align:"center" } 即可

**Comment by imooni** [comment]
如何配置默认居中呢？ 翻了文档没有找到  @greper
