### ISSUE TITLE
0.13.0 版本缺陷

### ISSUE THREAD

**Issue by levin950825** [fast-crud/fast-crud#7]
## FsButton 中使用 iconfy 无效
-  fs-button没有引用fs-icon

## label超出后未换行
![image](https://user-images.githubusercontent.com/13896536/124411827-da6b9200-dd7f-11eb-8853-9271a4b1dca9.png)

## 折叠按钮触发后告警
![image](https://user-images.githubusercontent.com/13896536/124411884-f838f700-dd7f-11eb-8100-880d16019062.png)
## 嵌套子表单弹窗后标签错位
![image](https://user-images.githubusercontent.com/13896536/124411913-0555e600-dd80-11eb-954f-d3ea7f854513.png)

**Comment by greper** [comment]
1、FsButton 中使用 iconfy 无效 ： 已修复
2、label超出后未换行： 自己覆盖样式吧
3、按钮折叠设置文字后依旧有： 配置rowHandle.more.icon=null
4、折叠按钮触发后告警：已修复
5、嵌套子表单弹窗后标签错位： 未复现

**Comment by levin950825** [comment]
已解决
