### ISSUE TITLE
fs-in-vben-starter正式打包运行报错无法进入登陆页面

### ISSUE THREAD

**Issue by jiliapp** [fast-crud/fast-crud#71]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`
fs-in-vben-starter正式打包运行报错无法进入登陆页面
### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`
pnpm  serve  本地跑无问题,可以登陆进入系统界面
pnpm build 后,放在服务器上后,停在loading页面,控制台代码报错.

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`
![1e96136e0a5edfdcb2b5be215c4ddb0](https://user-images.githubusercontent.com/78712770/176585734-7eaddb46-4e68-4593-a32b-861453ac7146.png)

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![f884aa7d5108381bbf349c98444b09f](https://user-images.githubusercontent.com/78712770/176585983-3079def2-1058-496b-b8fb-80367efcb174.png)

### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [x] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
升级到1.2.3试试
