### ISSUE TITLE
打包运行报错无法进入登陆页面

### ISSUE THREAD

**Issue by xuuui** [fast-crud/fast-crud#74]
控制台报错Uncaught SyntaxError: Unexpected token '...'

### 1. fast-crud版本：
`1.2.0`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [x ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
升级到1.2.3试试
