### ISSUE TITLE
潜在的typescript错误

### ISSUE THREAD

**Issue by whitemay** [fast-crud/fast-crud#75]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
crud.ts文件中，type ColumnCompositionProps的定义存在瑕疵，valueBuilder和valueResolve没有定义为可选的属性，在typescript检查中可能造成错误。一般情况下，crud.js文件中定义column时并不会设置这两个function。
建议定义为：
```
export type ColumnCompositionProps = {
...
  valueBuilder?: ({ value, key, row, form, index, mode }) => void;
  valueResolve?: (context: any) => void;
...
}
```

**Comment by greper** [comment]
1.2.7已修复
