### ISSUE TITLE
[fs-cell] doComputed 放在render函数里面每次更新都会重新执行一次

### ISSUE THREAD

**Issue by aov2005** [fast-crud/fast-crud#79]
https://github.com/fast-crud/fast-crud/blob/b1ca0b551327b731273676da996df903f57832a6/packages/fast-crud/src/components/crud/fs-cell.jsx#L20

为啥要放在这呢？在新版vue里面似乎也会造成死循环

**Comment by greper** [comment]
这里以前是放render外面的，以前版本没啥问题。 后面不知道什么时候起，列设置修改之后，单元格内容配置无效了，全部变成了text，暂时没找到原因，就临时把它放到render里面先

**Comment by greper** [comment]
找到原因了，我修复一下
