### ISSUE TITLE
fs-in-vben-starter表格查询栏不美观

### ISSUE THREAD

**Issue by weaselveehuang** [fast-crud/fast-crud#80]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
fs-in-vben-starter表格查询栏不美观，期望与原框架vben展现一致。
多行查询条件时，各行label不能靠右对齐，查询和重置按钮也不能右对齐，即使配置了buttonsPosition: 'right'；
收缩展开按钮或链接期望跟随查询重置按钮。

### 复现步骤
columns配置多个查询条件，search: true；
search:{
        layout: 'multi-line',
}

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![image](https://user-images.githubusercontent.com/29849289/181216355-71f949c5-3e5e-4199-bf28-21211463833e.png)
![image](https://user-images.githubusercontent.com/29849289/181216406-6cb60f7e-7687-4571-8840-507c29e4e8a4.png)

#### 2. 实际效果
![image](https://user-images.githubusercontent.com/29849289/181216150-b7f2acdd-d2c5-4d63-ba6f-2fef45059616.png)

### 1. fast-crud版本：
1.2.7
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [ ] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [x] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
可以看 antdv版的多行示例配置 http://fast-crud.docmirror.cn/antdv/#/crud/feature/search-multi
![image](https://user-images.githubusercontent.com/1687298/181396967-1a0b2c1d-835a-42ea-acc2-e4db1534c5bd.png)
