### ISSUE TITLE
好看ui模板，建议引入，https://docs.soybean.pro/

### ISSUE THREAD

**Issue by SnowDra** [fast-crud/fast-crud#82]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`请在此处简要描述你所遇到的问题，必要时请贴出相关截图辅助理解和定位`

### 复现步骤
`请描述复现问题的详细步骤`
`如果非示例页面的问题，最好能提供最小复现示例的代码、或者仓库链接`

### 代码截图
`请贴出出错的相关代码截图`

### 报错截图
`请贴出报错日志截图`

### 效果截图
`请贴出效果截图`
### 1. fast-crud版本：
`请您填写fast-crud的版本`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [ ] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [x] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by crstudio** [comment]
这个界面还行吧，也就登录页面和tab标签好看点儿，其他都不如原生。个人鄙建。

**Comment by greper** [comment]
tab标签确实好看

**Comment by SnowDra** [comment]
这套代码写的也不错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fast-crud/fast-crud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月18日(星期三) 下午3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fast-crud/fast-crud] 好看ui模板，建议引入，https://docs.soybean.pro/ (Issue #82)





 
tab标签确实好看

**Comment by dongyanghe** [comment]
[soybean](https://github.com/fast-crud/fast-crud/issues/82#top)就是这个吧：https://yiming_chang.gitee.io/pure-admin-doc/pages/start/

**Comment by greper** [comment]
已支持
http://fast-crud.docmirror.cn/soybean/#/
https://github.com/fast-crud/fs-in-soybean-admin
