### ISSUE TITLE
BUG: 搜索栏的文本输入框的的全部清楚按钮会额外增加宽度

### ISSUE THREAD

**Issue by crstudio** [fast-crud/fast-crud#83]
## 一、问题描述
搜索栏的文本输入框，一旦输入了文字，会自动弹出清楚全部的小按钮，但是此时这个input的宽度也会增加，这个应该也是bug

### 1. fast-crud版本：
`1.2.7`
### 2. 使用的ui库以及版本
- [x] ElementPlus（版本？）

### 3. 使用的admin框架
- [x] 其他：`自己写的`

**Comment by greper** [comment]
截个图呀

**Comment by greper** [comment]
已解决
