### ISSUE TITLE
fast-curd全局配置切换多语言时 部分字段没有翻译成目标语言

### ISSUE THREAD

**Issue by zhaohejing** [fast-crud/fast-crud#88]
> 感谢您支持fast-crud，请按如下规范提交issue    
> 如果有条件，请尽量在[github上提交](https://github.com/fast-crud/fast-crud/issues)

## 一、问题描述
`fast-curd全局配置切换多语言时 部分字段没有翻译成目标语言`

### 复现步骤
`[示例地址](http://fast-crud.docmirror.cn/antdv/#/crud/component/text)
打开示例页面 左上角选择切换语言为英语
`

### 代码截图
![image](https://user-images.githubusercontent.com/8697366/188805615-b0fe8d3d-0e2e-4665-a3f9-912d00af2bb7.png)

### 报错截图
![image](https://user-images.githubusercontent.com/8697366/188805615-b0fe8d3d-0e2e-4665-a3f9-912d00af2bb7.png)

### 效果截图
![image](https://user-images.githubusercontent.com/8697366/188805710-caa4dba6-5f66-4a4a-9073-4e53bd7908c0.png)

### 1. fast-crud版本：
`    "@fast-crud/fast-crud": "^1.3.0",
    "@fast-crud/fast-extends": "^1.3.0",
    "@fast-crud/ui-antdv": "^1.3.0",`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [ ] 其他：`请注明`

**Comment by greper** [comment]
1.4.0 已修复
