### ISSUE TITLE
讨论，打开新增弹窗时，为何要调用 infoRequest 请求

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#90]
## 一、问题描述
打开新增弹窗时，调用了`infoRequest`请求，但此时 `row`是undefined啊。为何要调用`infoRequest`请求？场景是怎样的？

尽管我可以使用 `context.mode` === 'add'进行hack判断，不调用 `infoRequest`请求，但不理解这种场景下为何有`infoRequest`请求。求赐教

### 复现步骤
我的业务场景，「新增」按钮在搜索栏下方。
点击「新增」时，会调用配置的`infoRequest`请求
![image](https://user-images.githubusercontent.com/5880014/190054473-c64ca2c3-5b83-40e7-914c-e349b5c41fa1.png)

### 代码截图
源码中发现这段，是bug吗？因为此时 `row`是`undefined`啊
![image](https://user-images.githubusercontent.com/5880014/190054805-8942d75b-7d26-4589-896f-5036ab355774.png)

### 报错截图
![image](https://user-images.githubusercontent.com/5880014/190054786-afe2000d-d835-43b7-9135-b76366763d90.png)

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.2.2",
"@fast-crud/ui-antdv": "^1.2.2",
### 2. 使用的ui库以及版本
"ant-design-vue": "^3.2.9",

### 3. 使用的admin框架
- [x] fs-admin-antdv

**Comment by greper** [comment]
可能在某些情况下添加需要请求默认值
你可以判断一下mode!=add
