### ISSUE TITLE
column.show不支持compute吗

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#92]
## 一、问题描述
column.show 不支持通过compute()设置显示隐藏吗？

### 复现步骤
```
// 以下写法是生效的
column: {
    show: false
}
```
```
// 以下写法是无效的
column: {
    show: compute(() => {
         return false
    })
}
```

#### 1. 期望效果
希望可以通过compute()动态设置column.show

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.3.0",
"@fast-crud/ui-antdv": "^1.3.0",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv ("^3.2.9")

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
不支持，因为列的显示和隐藏不应该跟行相关。你可以直接给column.show配置ref或computed
