### ISSUE TITLE
fs-form-wrapper可以支持每次关闭时移除dom吗

### ISSUE THREAD

**Issue by jingjingzhao** [fast-crud/fast-crud#94]
## 一、问题描述
fs-form-wrapper可以支持每次关闭时移除dom吗？
每次点击「新增」时，创建新的`fs-form-wrapper`弹窗，关闭后从dom中移除它。再次新增，再创建新的dom。
业务场景：每次点击「新增」后，会实时获取部分下拉选数据，如果不移除dom，没办法再次获取动态数据
![image](https://user-images.githubusercontent.com/5880014/191488024-40002ad5-528b-4efb-9af9-477ac8b24661.png)

### 1. fast-crud版本：
"@fast-crud/fast-crud": "^1.2.0",
"@fast-crud/ui-antdv": "^1.2.0",
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv 

### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [x] fs-admin-antdv

**Comment by greper** [comment]
antdv的modal组件支持此功能，将destroyOnClose配置到form.wrapper下即可
![image](https://user-images.githubusercontent.com/1687298/193378344-d511cc2c-acd1-4178-80ed-0b9c7388193e.png)

**Comment by greper** [comment]
你这里的问题可能不是销毁子元素能够解决的
本质上是dict对象内缓存了字典，它只会请求一次，所以你应该保留dict的ref，在打开对话框的事件里面dictRef.reloadDict()
