### ISSUE TITLE
使用dict-tree组件，表格展示背景为什么是黑色

### ISSUE THREAD

**Issue by heiyangk** [fast-crud/fast-crud#97]
## 一、问题描述
使用dict-tree组件，表格展示背景为什么是黑色

### 效果截图
`请贴出效果截图`
#### 1. 期望效果
![image](https://user-images.githubusercontent.com/33884924/192752077-9f068959-fcfa-4601-8b65-0617635d5300.png)

#### 2. 实际效果
![image](https://user-images.githubusercontent.com/33884924/192752029-daae012e-1af0-4020-943c-c1cc47782c16.png)

### 1. fast-crud版本：
`1.3.0`
### 2. 使用的ui库以及版本
`中括号中输入x即选中，或者删除其他，仅保留你正使用的ui库`
- [x] Antdv (版本？3.2.12)
- [ ] ElementPlus（版本？）
- [ ] NaiveUI（版本？）
- [ ] 
### 3. 使用的admin框架
`请您填写您当前使用的admin框架是哪一套`
- [] fs-admin-antdv
- [ ] fs-admin-element
- [ ] fs-admin-naive
- [ ] fs-in-vben
- [ ] vben-admin
- [ ] cool-admin
- [x] 其他：`集成到自己项目`

**Comment by greper** [comment]
你的字典数据里面是否有color字段
